### ISSUE TITLE
Feature - Support Entity Groups

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [MindFreeze/ha-sankey-chart#103]
So, I have been having great success using this to plot my home's energy utilization from source, to consumer.

![image](https://user-images.githubusercontent.com/5262735/226121495-01980eee-bcd5-4d2d-9a95-27ae4e9fa507.png)

![image](https://user-images.githubusercontent.com/5262735/226121593-9ba4a3e6-a221-450e-8257-5b70144b6022.png)

However, while I have been making these diagrams- I thought of a way which would make this much nicer. The ability to configure things using groups.

Say, for example, instead of this:

``` yaml
  - entities:
      - entity_id: sensor.load_power_essential
        color: blue
        children:
          - sensor.bedroom_power
          - sensor.lights_power
          - sensor.server_power
      - entity_id: sensor.load_power_non_essential
        color: yellow
        children:
          - sensor.dishwasher_power
          - sensor.dryer_power
          - sensor.garage_power
          - sensor.kitchen_power
          - sensor.livingroom_power
          - sensor.hvac_total_power
          - sensor.noncritical_other_loads
          - untracked
  - entities:
      - entity_id: sensor.server_power
        color: plum
        children:
          - sensor.kube01_current_consumption
          - sensor.kube05_current_consumption
          - sensor.kube06_current_consumption
          - sensor.unifi_aggregation_switch_current_consumption
          - sensor.nvr_current_consumption
          - sensor.kasa_smart_plug_383a_2_current_consumption
          - sensor.truenas_power
          - Server - Other
      - entity_id: sensor.bedroom_power
        name: Office
        color: LightBlue
        children:
          - sensor.gaming_pc_current_consumption
          - sensor.wife_pc_current_consumption
          - sensor.monitors_current_consumption
          - sensor.internet_current_consumption
          - sensor.work_pc_current_consumption
          - sensor.bedroom_switch_current_consumption
          - Office - Other
```

We could specify this:

``` yaml
  - entities:
      - entity_id: sensor.load_power_essential
        color: blue
        remaining: untracked_critical
        children_group: group.power_rollup_load_power_essential
      - entity_id: sensor.load_power_non_essential
         children_group: group.power_rollup_load_power_non_essential
  - entities:
      - entity_id: sensor.server_power
        color: plum
        children_group: group.power_rollup_server
        children_group_remaining: 
            name: Server - Other
      - entity_id: sensor.bedroom_power
        name: Office
        color: LightBlue
        children_group: group.power_rollup_office_essential
        children_group_remaining: 
            name: Office - Other
```

If, such a thing were feasible, it would make it easily possible to reuse the groups for other dashboard panels as well.

Lastly, I think this would improve the overall usability, and reduce the amount of configuration required. Potentially.

Just- an idea.
