### ISSUE TITLE
Incorrect line width when using subtract_entities:

### ISSUE THREAD

**Issue by Ralphy140** [MindFreeze/ha-sankey-chart#111]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:** 

1.12

**Last working release (if known):** 

NA

**Browser and Operating System:**

**Description of problem:**

When using the subtract_entities: function it does successfully subtract the value of the entity to describe the value in the bar. The corresponding line width does not shrink to match the new value represented in the bar and stays the same width as before the subtract function was used. 

**Javascript errors shown in the web inspector (if applicable):**

```


```

**Additional information:**

![Screenshot 2023-04-21 at 3 47 30 pm](https://user-images.githubusercontent.com/85327073/233550783-521a95d4-423b-4215-adff-672263a9efc7.png)

**Comment by MindFreeze** [comment]
I can't reproduce this. Does it still happen and can you provide more info, like a screenshot that includes the previous section and/or the config used?

**Comment by iamnotralphy** [comment]
This is the relevent section of code that i have configured 

```
  - entities:
      - entity_id: sensor.powerwall_battery_import
        color: var(--success-color)
        name: Import
        children:
          - charge
          - sensor.apc_batter2grid_kwh_total
      - entity_id: loss
        type: remaining_parent_state
        name: Loss
        color: gray
      - entity_id: sensor.apc_total_house_kwh
        color: '#3476CB'
  - entities:
      - entity_id: charge
        type: remaining_parent_state
        name: Charge Loss
        color: gray
        subtract_entities:
          - sensor.apc_battery2house_kwh
    ```
