### ISSUE TITLE
remaining_parent_state doesn't work

### ISSUE THREAD

**Issue by realjax** [MindFreeze/ha-sankey-chart#119]
No matter what I tried, I cant get the 'remaining_parent_state' type to work..

```
height: 200
unit_prefix: k
round: 2
min_box_height: 3
min_box_distance: 10
show_states: true
show_units: true
sections:
  - entities:
      - type: entity
        children:
          - sensor.stroomdagverbruik
        entity_id: sensor.energy_usage_today
        name: Eneco
      - type: entity
        children:
          - sensor.stroomdagverbruik
          - sensor.teruglevering
        entity_id: sensor.envoy_122305062754_today_s_energy_production
        name: zonnepanelen
        color: var(--warning-color)
  - entities:
      - type: entity
        children:
          - sensor.verbruikdagelijks_tvaudio
          - sensor.verbruikdagelijks_qookervaatwasser2
          - sensor.verbruikdagelijks_wasmachine
          - sensor.verbruikdagelijks_gamezolder
          - sensor.verbruikdagelijks_droger
        entity_id: sensor.stroomdagverbruik
      - type: entity
        children: []
        entity_id: sensor.teruglevering
        color: var(--success-color)
  - entities:
      - type: entity
        children: []
        name: TV audio
        color: red
        entity_id: sensor.verbruikdagelijks_tvaudio
      - type: entity
        children: []
        name: qook/vaat
        color: red
        entity_id: sensor.verbruikdagelijks_qookervaatwasser2
      - type: entity
        children: []
        name: wasmachine
        color: red
        entity_id: sensor.verbruikdagelijks_wasmachine
      - type: entity
        children: []
        name: droger
        color: red
        entity_id: sensor.verbruikdagelijks_droger
      - type: entity
        children: []
        name: gamezolder
        color: red
        entity_id: sensor.verbruikdagelijks_gamezolder
      - type: remaining_parent_state
        children: []
        entity_id: whatever333
        name: overig
type: custom:sankey-chart
show_names: true
wide: false
min_state: 0
show_icons: false
energy_date_selection: false

```

results in 
![Screenshot 2023-07-21 at 11 10 57](https://github.com/MindFreeze/ha-sankey-chart/assets/883435/686faa89-746e-4564-80d6-48d262f0ecad)
