### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by AleXSR700** [MindFreeze/ha-sankey-chart#12]
**Is your feature request related to a problem? Please describe.**
Not a problem. It would just be nice to be able to use wildcards, similar to auto-entities.

e.g.
sensor.*_power

**Describe the solution you'd like**
Support for wildcards such as 
entities: sensor.*_power

**Describe alternatives you've considered**
Using auto-entities card, but not sure if that even works with Sankey card and it would be nicer to have this as an integrated feature.

**Additional context**

**Comment by MindFreeze** [comment]
I can see this being useful when defining children but not so much for the main section entities. Unless it is last section with no children and you don't want to define names, colors or any other customizations, which seems kinda edgy.

**Comment by AleXSR700** [comment]
Well, my first section would e.g. be the sum of all consumers (since I cannot measure the grid directly). 
The sum would be sensors.*_power
and then the next section would be the different areas (indoors & outdoors) and then ... wait, I will draw it differently

sensors.*_power (wildcard only)
---
indoors &  indoors (wildcard + filter indoor/outdoor)
-----
indoors areas and outdoors  areas (wildcard + filter area)
---------
indoors areas consumers & outdoort areas consumers (wildcard + filter area)


These levels/children would all be created on-the-fly if wildcards and filters were available. Unlike e.g. HA Energy, where you have to manually add each new consumer (which is currently also the case for the Sankey card).

**Comment by MindFreeze** [comment]
But how would you configure the connections in yaml?

Right now each entity has children. If you deifne all entities with sensor.*_power, then I don't see a way to define children per entity without listing them explicitly. And if you list them anyway, the wildcard would be pointless.

**Comment by AleXSR700** [comment]
This is based on your https://github.com/MindFreeze/ha-sankey-chart#daily-energy-use
So the chart would look similar to that but with my above scheme.

Hope I did not make a logical error (since I cannot test it yet) but I think it would be along the lines of this (with wildcards & filters needed for sections and children.
```
- type: custom:sankey-chart
  show_names: true
  unit_prefix: k
  round: 1
  wide: true
  sections:
    - entities:
        - entity_id: sensor.*_power       #first level with total consumed power
    - entities:
        - entity_id: sensor.*_power
            filter:
              entity_id: *.*outdoors
          children:
            - sensor.*outdoors
        - entity_id: sensor.*_power
            filter:
              entity_id: *.*indoors
          children:
            - sensor.*indoors
    - entities:
        - entity_id: sensor.*indoors
            filter:
              area: living_room
          children:
            - sensor.*_power
                filter: 
                  area: living_room
        - entity_id: sensor.*indoors
            filter:
              area: dining_room
          children:
            - sensor.*_power
                filter: 
                  area: dining_room
        - entity_id: sensor.*outdoors
            filter:
              area: garage
          children:
            - sensor.*_power
                filter: 
                  area: garage
        - entity_id: sensor.*outdoors
            filter:
              area: garden
          children:
            - sensor.*_power
                filter: 
                  area: garden

```
