### ISSUE TITLE
Error: Missing connection: sensor.power1 - sensor.power2

### ISSUE THREAD

**Issue by segdy** [MindFreeze/ha-sankey-chart#121]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** 1.14.0

**Browser and Operating System:** MacOS Ventura, Chrome and HA app.

**Description of problem:**

This error does not make sense at all and I have no clue why it shows up. I am building my power flow, grid and solar as input, then first consumption meter, then sub panel, then both phases and then consumers. So far I added 4 large consumers: Heat pump, water heater, Unit B and upper floor. All of these use both phases and are in their behavior identical! So I added all of them as children to both phases.

This works as expected for heat pump, water heater and upper floor. However, despite identical in principle, I get the following error when I add Unit B:

**Error: Missing connection: sensor.vue2sub1_phase_b_power - sensor.vue2sub1_unit_b_power**

Why?

```
type: custom:sankey-chart
show_names: true
wide: true
sections:
  - entities:
      - entity_id: sensor.watts_consumed
        name: Grid
        children:
          - sensor.envoy_202239162660_current_power_consumption
      - entity_id: sensor.envoy_202239162660_current_power_production
        name: Solar
        children:
          - sensor.envoy_202239162660_current_power_consumption
  - entities:
      - entity_id: sensor.envoy_202239162660_current_power_consumption
        name: Envoy
        children:
          - sensor.vue2sub1_total_power
  - entities:
      - entity_id: sensor.vue2sub1_total_power
        name: Subpanel
        children:
          - sensor.vue2sub1_phase_a_power
          - sensor.vue2sub1_phase_b_power
  - entities:
      - entity_id: sensor.vue2sub1_phase_a_power
        name: Phase A
        children:
          - sensor.vue2sub1_heat_pump_power
          - sensor.vue2sub1_water_heater_power
          - sensor.vue2sub1_unit_b_power
          - sensor.vue2sub1_upper_floor_power
      - entity_id: sensor.vue2sub1_phase_b_power
        name: Phase B
        children:
          - sensor.vue2sub1_heat_pump_power
          - sensor.vue2sub1_water_heater
          - sensor.vue2sub1_upper_floor_power
          - sensor.vue2sub1_unit_b_power
  - entities:
      - entity_id: sensor.vue2sub1_heat_pump_power
        name: Heat Pump
      - entity_id: sensor.vue2sub1_water_heater_power
        name: Water Heater
      - entity_id: sensor.vue2sub1_unit_b_power
        name: ADU
      - entity_id: sensor.vue2sub1_upper_floor_power
        name: Upper Floor
```

**Additional information:**
