### ISSUE TITLE
Children issue

### ISSUE THREAD

**Issue by roumano** [MindFreeze/ha-sankey-chart#137]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

Some sensor are not show as children, please found a cleaned and as much simple as possible code to reproduce the issue : 

```
type: custom:sankey-chart
sections:
  - entities:
      - entity_id: sensor.emporiavue2_phase_c_power
        name: Ligne D
        color: cyan
        children:
          - sensor.emporiavue2_circuit_6_power
          - sensor.emporiavue2_circuit_14_power
          - sensor.emporiavue2_circuit_15_power
  - entities:
      - entity_id: sensor.emporiavue2_circuit_6_power
      - entity_id: sensor.emporiavue2_circuit_14_power
      - entity_id: sensor.emporiavue2_circuit_15_power
```

I don't known why but i didn't see the connection of  the `sensor.emporiavue2_circuit_6_power` to his parent sensor.emporiavue2_phase_c_power

![Capture d’écran du 2023-10-17 12-58-13](https://github.com/MindFreeze/ha-sankey-chart/assets/6402894/90a99b2f-409f-48db-ae22-72a5293a2b30)
