### ISSUE TITLE
Sankey Chart Card Not Displaying Solar Energy Generation Data

### ISSUE THREAD

**Issue by filoor** [MindFreeze/ha-sankey-chart#152]
## Environment
- Home Assistant Version: [e.g., 2023.11.3]
- Sankey Chart Card Version: [e.g., 1.18.0]

## Describe the issue
I'm using the Sankey Chart Card to visualize my energy flow, including energy consumption and generation. While the card correctly shows consumption, it does not display the energy being generated by my solar panels despite the panels actively generating power.

## Steps to Reproduce
1. Go to the Sankey Chart Card on my dashboard.
2. Observe the energy flow.
3. Notice that solar panel generation is missing from the display.

## Expected behavior
I would expect the Sankey Chart to show all energy flows, including solar panel generation, as part of the energy distribution.

## Actual behavior
The solar panel generation is not displayed on the Sankey Chart, although other energy flows are visible.

## Additional information
Here's the code I'm using for the Sankey Chart Card:

```yaml
height: 200
unit_prefix: ''
round: 1
min_box_height: 3
min_box_distance: 5
show_states: true
show_units: true
sections:
  - entities:
      - type: entity
        children:
          - sensor.total_energy_woonkamer
          - sensor.total_energy_keuken
          - sensor.total_energy_washok
        entity_id: sensor.kwh_meter_3_phase_active_power
        color_on_state: false
      - type: entity
        children:
          - sensor.total_energy_woonkamer
          - sensor.total_energy_keuken
          - sensor.total_energy_washok
        entity_id: sensor.p1_meter_active_power
        color_on_state: false
  - entities:
      - type: entity
        children:
          - sensor.0x70b3d52b60043bf0_power
        entity_id: sensor.total_energy_woonkamer
      - type: entity
        children:
          - sensor.0x70b3d52b6004245a_power
          - sensor.vaatwasser_power
        entity_id: sensor.total_energy_keuken
      - type: entity
        children:
          - sensor.0x70b3d52b600425fd_power
          - sensor.spiegel_power
        entity_id: sensor.total_energy_washok
    sort_group_by_parent: false
  - entities:
      - type: entity
        children: []
        entity_id: sensor.0x70b3d52b60043bf0_power
      - type: entity
        children: []
        entity_id: sensor.0x70b3d52b6004245a_power
      - type: entity
        children: []
        entity_id: sensor.vaatwasser_power
      - type: entity
        children: []
        entity_id: sensor.0x70b3d52b600425fd_power
      - type: entity
        children: []
        entity_id: sensor.spiegel_power
    sort_group_by_parent: false
type: custom:sankey-chart
show_names: true
wide: false
show_icons: true
```
Attached is a screenshot that clearly shows the solar panels are generating power, yet the Sankey Chart does not reflect this.
<img width="428" alt="Scherm­afbeelding 2023-11-28 om 11 00 32" src="https://github.com/MindFreeze/ha-sankey-chart/assets/3647638/833c099d-f790-4213-b32e-11cb9563d91c">

I suspect that the solar energy generation data is displayed as a negative value, which could be why it's not being visualized correctly on the Sankey Chart Card.
