### ISSUE TITLE
Not all branch connectors get rendered

### ISSUE THREAD

**Issue by amaximus** [MindFreeze/ha-sankey-chart#17]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
0.6.3

**Last working release (if known):**

**Browser and Operating System:**
Chrome 101.0.4951.67 on Windows 10

**Description of problem:**
Not all branch connectors get rendered.

The config does not show branch connector between RF433 and Wemo1:
```
      - type: custom:sankey-chart
        show_names: true
        show_icons: true
        min_box_height: 40
        wide: true
        height: 300
        sections:
          - entities:
              - entity_id: sensor.mqtt
                children:
                  - sensor.dep_wemo_d1_1
                  - sensor.dep_nodemcu
              - entity_id: sensor.dep_sonoff_rf433
                children:
                  - sensor.dep_wemo_d1_1
          - entities:
              - entity_id: sensor.dep_nodemcu
                children:
                  - sensor.dep_garage_door
                  - sensor.dep_sonoff_zigbee
              - entity_id: sensor.dep_wemo_d1_1
                children:
                  - sensor.dep_lifting_pump
                  - sensor.dep_irrigation_control
          - entities:
              - sensor.dep_garage_door
              - sensor.dep_sonoff_zigbee
              - sensor.dep_lifting_pump
              - sensor.dep_irrigation_control
```
![tree](https://user-images.githubusercontent.com/2511168/170440387-5b4ab2ed-55d1-402f-b143-912d30963091.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
