### ISSUE TITLE
Add "Filters" to Scale or Otherwise Transform Data

### ISSUE THREAD

**Issue by kaijk** [MindFreeze/ha-sankey-chart#170]
Rather than create a new template entity, please consider providing a way to transform the data.  I suggest starting with `multiply`, but other filters could be added as well.
```
entity_id: sensor.solar_watts
filters:
  - multiply: 0.001 # kW from W
  - multiply: -1 # invert negative to positive values
  - integrate: h # create kWh from kW
```

**Comment by MindFreeze** [comment]
Integrals will not be easy because historical data is needed, so it would only work with energy_date_selection and the accuracy may not be great.
Multiplying to convert W to kW shouldn't be necessary because the card handles this already. There may be a case for kcal to Wh, mi to km, etc.
I see the value in converting negative values to positive as this is needed often.
But overall, all of this can be done easily with HA template entities so I consider it very low priority.

**Comment by slyoldfox** [comment]
@kaijk 
Stumbled upon this issue when trying to "invert" a value (mainly to subtract energy production sensor).
I managed to do this by including the production sensor as a normal "entity" type, and in the 2nd section using a `- type: remaining_parent_state` where I `subtract_entities` the production sensors. Note that you have to specify each sensor twice, because it's already adding that sensor to the sum.

```
sections:
  - entities:
      - type: entity
        children:
          - sensor.total_energy
        entity_id: sensor.modbus_ac_energy_kwh
        color: var(--warning-color)
        name: Solar
      - type: entity
        children:
          - sensor.total_energy
        name: Consumption Tarif 1
        entity_id: sensor.energy_consumption_tarif_1
      - type: entity
        children:
          - sensor.total_energy
        name: Consumption Tarif 2
        entity_id: sensor.energy_consumption_tarif_2
      - type: entity
        children:
          - sensor.total_energy
        name: Production Tarif 1
        color: var(--energy-grid-return-color)
        entity_id: sensor.energy_production_tarif_1
      - type: entity
        children:
          - sensor.total_energy
        name: Production Tarif 2
        color: var(--energy-grid-return-color)
        entity_id: sensor.energy_production_tarif_2
  - entities:
      - type: remaining_parent_state
        children:
          - sensor.shellyem_a4e57cba5163_channel_1_energy
          - entity_id: sensor.washer_energy
          - sensor.dishwasher_energy_consumption
          - sensor.slypro_energy
          - sensor.slymini_energy
          - entity_id: sensor.shelly_ventilatie_energy
          - sensor.total_remainder
        subtract_entities:
          - sensor.energy_production_tarif_1 
          - sensor.energy_production_tarif_1 # Subtract this again
          - sensor.energy_production_tarif_2
          - sensor.energy_production_tarif_2
        name: home
        entity_id: sensor.total_energy
```

![image](https://github.com/user-attachments/assets/d8c53652-2293-473d-861f-835f75b6d0b6)
