### ISSUE TITLE
Maximum call stack

### ISSUE THREAD

**Issue by iNaiks** [MindFreeze/ha-sankey-chart#171]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
-  v1.21.1

**Browser and Operating System:**
- Safari (Mac/iOS) and APP Home Assistant (iOS)

**Description of problem:**
Error: "RangeError: Maximum call stack size exceeded."

Occurs when creating card.

This is the diagram that I want to create:
![Diagrama skynkercadr HS](https://github.com/MindFreeze/ha-sankey-chart/assets/72868890/51de6cec-f751-437c-8e47-f508ac8afa81)

And this the code of the card. I've revised all the code to see the error but I can't find.

```
height: 450
unit_prefix: k
round: 2
convert_units_to: ''
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_height: 5
min_box_distance: 20
show_states: true
show_units: false
sections:


  - entities:
      - type: entity
        children:
          - sensor.bateria_in
          - sensor.consumo_casa
        entity_id: sensor.prod_paneles
        color: yellow
        color_on_state: true
        color_limit: 1
        color_above: green
        color_below: red
        icon: fas:solar-panel
        name: Solar
      - type: entity
        children:
          - sensor.consumo_casa
          - sensor.consumo_paneles
        entity_id: sensor.bateria_out
        color: orange
        name: Bateria
        color_on_state: true
        color_limit: 1
        color_above: red
        color_below: green
        icon: mdi:battery-minus
      - type: entity
        children:
          - sensor.consumo_casa
          - sensor.bateria_in
          - sensor.consumo_paneles
        entity_id: sensor.endesa_in
        color: red
        name: Endesa
        color_on_state: true
        color_above: red
        color_below: green
        color_limit: 1
        icon: mdi:transmission-tower-export



  - entities:
      - type: entity
        children:
          - sensor.consumo_aire_salon_cpq_power
          - sensor.consumo_aire_hab1_cpq_power
          - sensor.consumo_aire_hab2_cpq_power
          - sensor.boiler_casa_grande_power
          - sensor.boiler_casa_peq_power
          - sensor.aire_doble_power
          - sensor.aire_estrella_power
          - sensor.aire_sol_power
          - sensor.aire_luna_power
          - sensor.boiler_nico_power
          - casa_other
          - casa_peq
          - casa_grande
          - zulo_nico
          - acs_casa_grande
          - boilers_casa_pq
          - acs_casa_pq
          - sensor.secadora_casa_peq_power
          - sensor.lavadora_casa_peq_power
          - sensor.lavadora_casa_grande_power
          - sensor.bomba_piscina_power
          - sensor.cocina_induccion_casa_pq_channel_1_power
          - sensor.cocina_induccion_casa_pq_channel_2_power
          - sensor.boiler_alex_power
        entity_id: sensor.consumo_casa
        color: green
        name: Casa
        color_on_state: true
        color_limit: 2
        color_above: orange
        color_below: green
        icon: fas:house

      - type: entity
        children: []
        entity_id: sensor.bateria_in
        name: Bat-IN
        color_on_state: true
        color_limit: 1
        icon: mdi:battery-plus

      - type: entity
        children: []
        entity_id: sensor.consumo_paneles
        name: Paneles


  - entities: 

      - type: remaining_parent_state
        children:
          - sensor.bomba_piscina_power
          - sensor.boiler_casa_grande_power
          - acs_casa_grande
          - sensor.lavadora_casa_grande_power
        entity_id: casa_grande
        name: Casa Gr
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

      - type: remaining_parent_state
        children:
          - boilers_casa_pq
          - acs_casa_pq
          - sensor.lavadora_casa_peq_power
          - sensor.secadora_casa_peq_power
          - sensor.cocina_induccion_casa_pq_channel_2_power
          - sensor.cocina_induccion_casa_pq_channel_1_power
        entity_id: casa_peq
        name: Casa Peq
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green


      - type: remaining_parent_state
        children:
          - sensor.boiler_nico_power
        entity_id: zulo_nico
        name: Zulo
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green


      - type: remaining_parent_state
        children: []
        entity_id: casa_other
        name: Other Casa
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green


  - entities: 

      - type: entity
        children: []
        entity_id: sensor.bomba_piscina_power

      - type: entity
        children: []
        entity_id: sensor.boiler_casa_grande_power
        icon: mdi:water-boiler
        
      - type: remaining_parent_state
        children:
          - sensor.aire_doble_power
          - sensor.aire_sol_power
          - sensor.aire_estrella_power
          - sensor.aire_luna_power
        entity_id: acs_casa_grande
        name: ACs Casa Gr
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

      - type: entity
        children: []
        entity_id: sensor.lavadora_casa_grande_power
        icon: mdi:washing-machine

      - type: remaining_parent_state
        children:
          - sensor.boiler_alex_power
          - sensor.boiler_casa_peq_power
        entity_id: boilers_casa_pq
        name: Boilers Casa Pq
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

      - type: remaining_parent_state
        children:
          - sensor.consumo_aire_salon_cpq_power
          - sensor.consumo_aire_hab2_cpq_power
          - sensor.consumo_aire_hab1_cpq_power
        entity_id: acs_casa_pq
        name: ACs Casa Pq
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

      - type: entity
        children: []
        entity_id: sensor.lavadora_casa_peq_power
        icon: mdi:washing-machine

      - type: entity
        children: []
        entity_id: sensor.secadora_casa_peq_power
        icon: mdi:tumble-dryer

      - type: entity
        children: []
        entity_id: sensor.cocina_induccion_casa_pq_channel_2_power
        name: Induc. Pq
        icon: mdi:induction

      - type: entity
        children: []
        entity_id: sensor.cocina_induccion_casa_pq_channel_1_power
        name: Cocina/Horno


      - type: entity
        children: []
        entity_id: sensor.boiler_nico_power
        icon: mdi:water-boiler














  - entities:

      - type: entity
        children: []
        entity_id: sensor.aire_doble_power
        name: Aire Doble
        icon: mdi:air-conditioner

      - type: entity
        children: []
        entity_id: sensor.aire_estrella_power
        name: Aire Estrella
        icon: mdi:air-conditioner

      - type: entity
        children: []
        entity_id: sensor.aire_luna_power
        icon: fas:moon
        name: Aire Luna


      - type: entity
        children: []
        entity_id: sensor.aire_sol_power
        name: Aire Sol
        icon: mdi:air-conditioner


      - type: entity
        children: []
        entity_id: sensor.boiler_alex_power
        icon: mdi:water-boiler

      - type: entity
        children: []
        entity_id: sensor.boiler_casa_peq_power
        icon: mdi:water-boiler


      - type: entity
        children: []
        entity_id: sensor.consumo_aire_salon_cpq_power
        name: AC Salon pq


      - type: entity
        children: []
        entity_id: sensor.consumo_aire_hab2_cpq_power
        name: AC Alex
        icon: mdi:account

      - type: entity
        children: []
        entity_id: sensor.consumo_aire_hab1_cpq_power
        name: AC Hab1






energy_date_selection: false
type: custom:sankey-chart
wide: false
show_names: true
static_scale: 0
show_icons: true
min_state: 0.029

```

**Javascript errors shown in the web inspector (if applicable):**

```
"RangeError: Maximum call stack size exceeded."
```

**Additional information:**
Can't find what is the error 
Thanks

**Comment by iNaiks** [comment]
> @iNaiks I see an issue with your config. For example, if you look at `Casa Gr`, its children are also listed as children of its parent `Casa`. `children` must only list direct connection. Meaning it must not include grand children. So you should remove `Casa Gr`'s children from `Casa`. There are a few other such cases as well.
> It is still a bug that the card didn't offer a better error message but your config is invalid as it is.

Thanks for the info, sorry for the bad config.
Updated removing the `childrens` of `Casa Gr` but the same error appear. 
I revised that there is only one children in `remaining_parent_state`. I think is good but sure I make other mistake.


```
height: 450
unit_prefix: k
round: 2
convert_units_to: ''
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_height: 5
min_box_distance: 20
show_states: true
show_units: false
sections:


  - entities:
      - type: entity
        children:
          - sensor.bateria_in
          - sensor.consumo_casa
        entity_id: sensor.prod_paneles
        color: yellow
        color_on_state: true
        color_limit: 1
        color_above: green
        color_below: red
        icon: fas:solar-panel
        name: Solar
      - type: entity
        children:
          - sensor.consumo_casa
          - sensor.consumo_paneles
        entity_id: sensor.bateria_out
        color: orange
        name: Bateria
        color_on_state: true
        color_limit: 1
        color_above: red
        color_below: green
        icon: mdi:battery-minus
      - type: entity
        children:
          - sensor.consumo_casa
          - sensor.bateria_in
          - sensor.consumo_paneles
        entity_id: sensor.endesa_in
        color: red
        name: Endesa
        color_on_state: true
        color_above: red
        color_below: green
        color_limit: 1
        icon: mdi:transmission-tower-export




  - entities:
      - type: entity
        children:

          - casa_other
          - casa_peq
          - casa_grande
          - zulo_nico

        entity_id: sensor.consumo_casa
        color: green
        name: Casa
        color_on_state: true
        color_limit: 2
        color_above: orange
        color_below: green
        icon: fas:house

      - type: entity
        children: []
        entity_id: sensor.bateria_in
        name: Bat-IN
        color_on_state: true
        color_limit: 1
        icon: mdi:battery-plus

      - type: entity
        children: []
        entity_id: sensor.consumo_paneles
        name: Paneles




  - entities: 

      - type: remaining_parent_state
        children:
          - sensor.bomba_piscina_power
          - sensor.boiler_casa_grande_power
          - acs_casa_grande
          - sensor.lavadora_casa_grande_power
        entity_id: casa_grande
        name: Casa Gr
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

      - type: remaining_parent_state
        children:
          - boilers_casa_pq
          - acs_casa_pq
          - sensor.lavadora_casa_peq_power
          - sensor.secadora_casa_peq_power
          - sensor.cocina_induccion_casa_pq_channel_2_power
          - sensor.cocina_induccion_casa_pq_channel_1_power
        entity_id: casa_peq
        name: Casa Peq
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green


      - type: remaining_parent_state
        children:
          - sensor.boiler_nico_power
        entity_id: zulo_nico
        name: Zulo
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green


      - type: remaining_parent_state
        children: []
        entity_id: casa_other
        name: Other Casa
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green




  - entities: 

      - type: entity
        children: []
        entity_id: sensor.bomba_piscina_power

      - type: entity
        children: []
        entity_id: sensor.boiler_casa_grande_power
        icon: mdi:water-boiler
        
      - type: remaining_parent_state
        children:
          - sensor.aire_doble_power
          - sensor.aire_sol_power
          - sensor.aire_estrella_power
          - sensor.aire_luna_power
        entity_id: acs_casa_grande
        name: ACs Casa Gr
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

      - type: entity
        children: []
        entity_id: sensor.lavadora_casa_grande_power
        icon: mdi:washing-machine

      - type: remaining_parent_state
        children:
          - sensor.boiler_alex_power
          - sensor.boiler_casa_peq_power
        entity_id: boilers_casa_pq
        name: Boilers Casa Pq
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

      - type: remaining_parent_state
        children:
          - sensor.consumo_aire_salon_cpq_power
          - sensor.consumo_aire_hab2_cpq_power
          - sensor.consumo_aire_hab1_cpq_power
        entity_id: acs_casa_pq
        name: ACs Casa Pq
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

      - type: entity
        children: []
        entity_id: sensor.lavadora_casa_peq_power
        icon: mdi:washing-machine

      - type: entity
        children: []
        entity_id: sensor.secadora_casa_peq_power
        icon: mdi:tumble-dryer

      - type: entity
        children: []
        entity_id: sensor.cocina_induccion_casa_pq_channel_2_power
        name: Induc. Pq
        icon: mdi:induction

      - type: entity
        children: []
        entity_id: sensor.cocina_induccion_casa_pq_channel_1_power
        name: Cocina/Horno


      - type: entity
        children: []
        entity_id: sensor.boiler_nico_power
        icon: mdi:water-boiler





  - entities:

      - type: entity
        children: []
        entity_id: sensor.aire_doble_power
        name: Aire Doble
        icon: mdi:air-conditioner

      - type: entity
        children: []
        entity_id: sensor.aire_estrella_power
        name: Aire Estrella
        icon: mdi:air-conditioner

      - type: entity
        children: []
        entity_id: sensor.aire_luna_power
        icon: fas:moon
        name: Aire Luna


      - type: entity
        children: []
        entity_id: sensor.aire_sol_power
        name: Aire Sol
        icon: mdi:air-conditioner


      - type: entity
        children: []
        entity_id: sensor.boiler_alex_power
        icon: mdi:water-boiler

      - type: entity
        children: []
        entity_id: sensor.boiler_casa_peq_power
        icon: mdi:water-boiler


      - type: entity
        children: []
        entity_id: sensor.consumo_aire_salon_cpq_power
        name: AC Salon pq


      - type: entity
        children: []
        entity_id: sensor.consumo_aire_hab2_cpq_power
        name: AC Alex
        icon: mdi:account

      - type: entity
        children: []
        entity_id: sensor.consumo_aire_hab1_cpq_power
        name: AC Hab1






energy_date_selection: false
type: custom:sankey-chart
wide: false
show_names: true
static_scale: 0
show_icons: true
min_state: 0.029

```

**Comment by MindFreeze** [comment]
Managed to reproduce it. The error ocures because you have 2 `remaining_parent_state` entities under the same parent (casa_peq). This can't be calculated. Only 1 `remaining_parent_state` is allowed.
I will fix the error message and the docs.

**Comment by iNaiks** [comment]
Thanks!!! It seems to be working. I've changed all the `remaining_parent_state` with `remaining_child_state` except the `other_casa` and all works.
Thanks
Nico

**Comment by iNaiks** [comment]
Just updated to v.2.0.1 and the connections between `sensor.consumo_casa` and `casa_gr` & `casa_peq` are disconnected 
<img width="528" alt="Captura de pantalla 2024-04-15 a las 15 40 27" src="https://github.com/MindFreeze/ha-sankey-chart/assets/72868890/4c09f07a-11ec-4c60-a792-3b8779cc28c9">

**Comment by MindFreeze** [comment]
I don't see a connection in your config. Can you please post the latest config?

**Comment by MindFreeze** [comment]
@iNaiks Also please try v2.0.2

**Comment by iNaiks** [comment]
> @iNaiks Also please try v2.0.2

Updated to v2.02 and no change.
Is strage because at around 16:30 all was working on iOS app and now didn't work again. Maybe when there is consumption on all childrens of `sensor.consumo_casa` all works good. I'm trying some test to see if this is the problem.

This is the config with some annotations (###):

```
height: 600
unit_prefix: k
round: 2
convert_units_to: ''
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_height: 45
min_box_distance: 0
show_states: true
show_units: false
sections:
  - entities:
      - type: entity
        children:
          - sensor.bateria_in
          - sensor.consumo_casa
        entity_id: sensor.prod_paneles
        color: yellow
        color_on_state: true
        color_limit: 1
        color_above: green
        color_below: red
        icon: fas:solar-panel
        name: Solar

      - type: entity
        children:
          - sensor.consumo_casa
          - sensor.consumo_paneles
        entity_id: sensor.bateria_out
        color: orange
        name: Bateria
        color_on_state: true
        color_limit: 1
        color_above: red
        color_below: green
        icon: mdi:battery-minus

      - type: entity
        children:
          - sensor.consumo_casa
          - sensor.bateria_in
          - sensor.consumo_paneles
        entity_id: sensor.endesa_in
        color: red
        name: Endesa
        color_on_state: true
        color_above: red
        color_below: green
        color_limit: 1
        icon: mdi:transmission-tower-export


  - entities:
      - type: entity
        children: ### here there are the childrens of house consuption
          - casa_other
          - casa_peq
          - casa_grande
          - zulo_nico
        entity_id: sensor.consumo_casa
        color: green
        name: Casa
        color_on_state: true
        color_limit: 2
        color_above: orange
        color_below: green
        icon: fas:house

      - type: entity
        children: []
        entity_id: sensor.bateria_in
        name: Bat-IN
        color_on_state: true
        color_limit: 1
        icon: mdi:battery-plus

      - type: entity
        children: []
        entity_id: sensor.consumo_paneles
        name: Paneles


  - entities:
      - type: remaining_child_state
        children:
          - sensor.bomba_piscina_power
          - sensor.boiler_casa_grande_power
          - acs_casa_grande
          - sensor.lavadora_casa_grande_power
        entity_id: casa_grande ### frist children of house consumption
        name: C.GR
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green
      - type: remaining_child_state
        children:
          - boilers_casa_pq
          - acs_casa_pq
          - sensor.lavadora_casa_peq_power
          - sensor.secadora_casa_peq_power
          - sensor.cocina_induccion_casa_pq_channel_2_power
          - sensor.cocina_induccion_casa_pq_channel_1_power
        entity_id: casa_peq #### second children of house consumption
        name: C.PQ
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green
      - type: remaining_child_state
        children:
          - sensor.boiler_nico_power
        entity_id: zulo_nico #### third children of house consumption
        name: Zulo
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green
      - type: remaining_parent_state
        children: []
        entity_id: casa_other #### four children of house consumption
        name: Other Casa
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green


  - entities:
      - type: entity
        children: []
        entity_id: sensor.bomba_piscina_power
      - type: entity
        children: []
        entity_id: sensor.boiler_casa_grande_power
        icon: mdi:water-boiler
      - type: remaining_child_state
        children:
          - sensor.aire_doble_power
          - sensor.aire_sol_power
          - sensor.aire_estrella_power
          - sensor.aire_luna_power
        entity_id: acs_casa_grande
        name: ACs Casa Gr
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green
      - type: entity
        children: []
        entity_id: sensor.lavadora_casa_grande_power
        icon: mdi:washing-machine
      - type: remaining_child_state
        children:
          - sensor.boiler_alex_power
          - sensor.boiler_casa_peq_power
        entity_id: boilers_casa_pq
        name: Boilers Casa Pq
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green
      - type: remaining_child_state
        children:
          - sensor.consumo_aire_salon_cpq_power
          - sensor.consumo_aire_hab2_cpq_power
          - sensor.consumo_aire_hab1_cpq_power
        entity_id: acs_casa_pq
        name: ACs Casa Pq
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green
      - type: entity
        children: []
        entity_id: sensor.lavadora_casa_peq_power
        icon: mdi:washing-machine
      - type: entity
        children: []
        entity_id: sensor.secadora_casa_peq_power
        icon: mdi:tumble-dryer
      - type: entity
        children: []
        entity_id: sensor.cocina_induccion_casa_pq_channel_2_power
        name: Induc. Pq
        icon: mdi:induction
      - type: entity
        children: []
        entity_id: sensor.cocina_induccion_casa_pq_channel_1_power
        name: Cocina/Horno
      - type: entity
        children: []
        entity_id: sensor.boiler_nico_power
        icon: mdi:water-boiler


  - entities:
      - type: entity
        children: []
        entity_id: sensor.aire_doble_power
        name: Aire Doble
        icon: mdi:air-conditioner
      - type: entity
        children: []
        entity_id: sensor.aire_estrella_power
        name: Aire Estrella
        icon: mdi:air-conditioner
      - type: entity
        children: []
        entity_id: sensor.aire_luna_power
        icon: fas:moon
        name: Aire Luna
      - type: entity
        children: []
        entity_id: sensor.aire_sol_power
        name: Aire Sol
        icon: mdi:air-conditioner
      - type: entity
        children: []
        entity_id: sensor.boiler_alex_power
        icon: mdi:water-boiler
      - type: entity
        children: []
        entity_id: sensor.boiler_casa_peq_power
        icon: mdi:water-boiler
      - type: entity
        children: []
        entity_id: sensor.consumo_aire_salon_cpq_power
        name: AC Salon pq
      - type: entity
        children: []
        entity_id: sensor.consumo_aire_hab2_cpq_power
        name: AC Alex
        icon: mdi:account
      - type: entity
        children: []
        entity_id: sensor.consumo_aire_hab1_cpq_power
        name: AC Hab1
energy_date_selection: false
type: custom:sankey-chart
wide: false
show_names: true
static_scale: 0
show_icons: true
min_state: 0.029

```
Thanks!

**Comment by iNaiks** [comment]
<img width="515" alt="Captura de pantalla 2024-04-15 a las 21 05 30" src="https://github.com/MindFreeze/ha-sankey-chart/assets/72868890/d1f12f8d-fcf8-4253-9326-d51e6c05271b">

**Comment by iNaiks** [comment]
Some interesting with some test that I made was:

If the line 101 is `- type: remaining_child_state` of `entity_id: casa_grande` then shows this:

<img width="528" alt="Captura de pantalla 2024-04-15 a las 21 40 53" src="https://github.com/MindFreeze/ha-sankey-chart/assets/72868890/ba4ffd7c-e459-49f0-87da-40f34814cf4c">


If the line is changed to `- type: remaining_parent_state` then changes to:

<img width="507" alt="Captura de pantalla 2024-04-15 a las 21 43 43" src="https://github.com/MindFreeze/ha-sankey-chart/assets/72868890/5c0f3d3b-f04c-4b85-8935-1f6f0b51f769">


this is the code:

```
height: 600
unit_prefix: k
round: 2
convert_units_to: ''
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_height: 45
min_box_distance: 0
show_states: true
show_units: false
sections:






  - entities:
      - type: entity
        children:
          - sensor.bateria_in
          - sensor.consumo_casa
        entity_id: sensor.prod_paneles
        color: yellow
        color_on_state: true
        color_limit: 1
        color_above: green
        color_below: red
        icon: fas:solar-panel
        name: Solar

      - type: entity
        children:
          - sensor.consumo_casa
          - sensor.consumo_paneles
        entity_id: sensor.bateria_out
        color: orange
        name: Bateria
        color_on_state: true
        color_limit: 1
        color_above: red
        color_below: green
        icon: mdi:battery-minus

      - type: entity
        children:
          - sensor.consumo_casa
          - sensor.bateria_in
          - sensor.consumo_paneles
        entity_id: sensor.endesa_in
        color: red
        name: Endesa
        color_on_state: true
        color_above: red
        color_below: green
        color_limit: 1
        icon: mdi:transmission-tower-export


  - entities:
      - type: entity
        children: ### here there are the childrens of house consuption
          - casa_other
 #         - casa_peq
          - casa_grande
 #         - zulo_nico
        entity_id: sensor.consumo_casa
        color: green
        name: Casa
        color_on_state: true
        color_limit: 2
        color_above: orange
        color_below: green
        icon: fas:house

      - type: entity
        children: []
        entity_id: sensor.bateria_in
        name: Bat-IN
        color_on_state: true
        color_limit: 1
        icon: mdi:battery-plus

      - type: entity
        children: []
        entity_id: sensor.consumo_paneles
        name: Paneles


  - entities:
      - type: remaining_parent_state
        children: []
        entity_id: casa_other #### four children of house consumption
        name: Other Casa
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

      - type: remaining_child_state
        children:
          - sensor.bomba_piscina_power
          - sensor.boiler_casa_grande_power
          - acs_casa_grande
          - sensor.lavadora_casa_grande_power
        entity_id: casa_grande ### frist children of house consumption
        name: C.GR
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green

  - entities:
      - type: entity
        children: []
        entity_id: sensor.bomba_piscina_power
      - type: entity
        children: []
        entity_id: sensor.boiler_casa_grande_power
        icon: mdi:water-boiler
      - type: entity
        children: []
        entity_id: sensor.lavadora_casa_grande_power
        icon: mdi:washing-machine

      - type: remaining_child_state
        children:
          - sensor.aire_doble_power
          - sensor.aire_sol_power
          - sensor.aire_estrella_power
          - sensor.aire_luna_power
        entity_id: acs_casa_grande
        name: ACs Casa Gr
        icon: fas:house-medical-circle-exclamation
        color_on_state: true
        color_limit: 1.5
        color_above: purple
        color_below: green


  - entities:
      - type: entity
        children: []
        entity_id: sensor.aire_doble_power
        name: Aire Doble
        icon: mdi:air-conditioner
      - type: entity
        children: []
        entity_id: sensor.aire_estrella_power
        name: Aire Estrella
        icon: mdi:air-conditioner
      - type: entity
        children: []
        entity_id: sensor.aire_luna_power
        icon: fas:moon
        name: Aire Luna
      - type: entity
        children: []
        entity_id: sensor.aire_sol_power
        name: Aire Sol
        icon: mdi:air-conditioner




energy_date_selection: false
type: custom:sankey-chart
wide: false
show_names: true
static_scale: 0
show_icons: true
min_state: 0.029
```
