### ISSUE TITLE
Passthrough not working with remaining parent/child state. 

### ISSUE THREAD

**Issue by icefest** [MindFreeze/ha-sankey-chart#175]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
_v1.21.1_
**Last working release (if known):**
N/A, though I'm new to github 

**Browser and Operating System:**
chrome, 
Windows 11 Pro

**Description of problem:**

I have the following test environment: 
    Each item <Test #> is an input number - for debugging. 
I have both:
1)  remaining_parent_state, and 
2)  remaining_child_state

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/24628745/d244db68-d1e5-4f18-8880-99bd4738d216)

```
height: 800
show_states: false
sections:
  - entities:
      - type: entity
        children:
          - input_number.test_3
        entity_id: input_number.test_1
      - type: entity
        children:
          - input_number.test_3
          - remaining_parent
        entity_id: input_number.test_2
      - type: entity
        children:
          - remaining_child
        entity_id: input_number.test_7
  - entities:
      - type: entity
        children:
          - input_number.test_4
        entity_id: input_number.test_3
      - type: remaining_parent_state
        children:
          - input_number.test_6
        entity_id: remaining_parent
        name: Remaining Parent
      - type: remaining_child_state
        children:
          - input_number.test_6
        entity_id: remaining_child
        name: Remaining Child
  - entities:
      - type: entity
        children:
          - input_number.test_5
        entity_id: input_number.test_4
      - type: passthrough
        children:
          - input_number.test_6
        entity_id: input_number.test_6
  - entities:
      - type: entity
        children: []
        entity_id: input_number.test_5
      - type: entity
        children: []
        entity_id: input_number.test_6
type: custom:sankey-chart
show_names: true
title: Testing Enviroment
```

**Now, let's say I prefer having both parent states in section 3:
(Edited in paint)**
![image](https://github.com/MindFreeze/ha-sankey-chart/assets/24628745/3722dbfc-0360-40eb-8786-f474008325f7)

I think the way to do this is to move the below snippet from section 2 into section 3, and then delete the passthrough items so they are automagically recreated.
```
      - type: remaining_parent_state
        children:
          - input_number.test_6
        entity_id: remaining_parent
        name: Remaining Parent
      - type: remaining_child_state
        children:
          - input_number.test_6
        entity_id: remaining_child
        name: Remaining Child
```
This would result in the code as per below (before the automagic passthrough creation):
```
height: 800
show_states: false
sections:
  - entities:
      - type: entity
        children:
          - input_number.test_3
        entity_id: input_number.test_1
      - type: entity
        children:
          - input_number.test_3
          - remaining_parent
        entity_id: input_number.test_2
      - type: entity
        children:
          - remaining_child
        entity_id: input_number.test_7
  - entities:
      - type: entity
        children:
          - input_number.test_4
        entity_id: input_number.test_3
  - entities:
      - type: entity
        children:
          - input_number.test_5
        entity_id: input_number.test_4
      - type: remaining_parent_state
        children:
          - input_number.test_6
        entity_id: remaining_parent
        name: Remaining Parent
      - type: remaining_child_state
        children:
          - input_number.test_6
        entity_id: remaining_child
        name: Remaining Child
  - entities:
      - type: entity
        children: []
        entity_id: input_number.test_5
      - type: entity
        children: []
        entity_id: input_number.test_6
type: custom:sankey-chart
show_names: true
title: Testing Enviroment
```
But the above code gives me the following error: `Error: Entity not found "remaining_parent"`

I also tested coding the passthrough myself:
```
height: 800
show_states: false
sections:
  - entities:
      - type: entity
        children:
          - input_number.test_3
        entity_id: input_number.test_1
      - type: entity
        children:
          - input_number.test_3
          - remaining_parent
        entity_id: input_number.test_2
      - type: entity
        children:
          - remaining_child
        entity_id: input_number.test_7
  - entities:
      - type: entity
        children:
          - input_number.test_4
        entity_id: input_number.test_3
      - type: passthrough
        children:
          - remaining_child
        entity_id: remaining_child
      - type: passthrough
        children:
          - remaining_parent
        entity_id: remaining_parent
  - entities:
      - type: entity
        children:
          - input_number.test_5
        entity_id: input_number.test_4
      - type: remaining_parent_state
        children:
          - input_number.test_6
        entity_id: remaining_parent
        name: Remaining Parent
      - type: remaining_child_state
        children:
          - input_number.test_6
        entity_id: remaining_child
        name: Remaining Child
  - entities:
      - type: entity
        children: []
        entity_id: input_number.test_5
      - type: entity
        children: []
        entity_id: input_number.test_6
type: custom:sankey-chart
show_names: true
title: Testing Enviroment
```
No Dice, same error. 
![image](https://github.com/MindFreeze/ha-sankey-chart/assets/24628745/e6b66f4d-ea15-4359-9c23-f5eec892fc52)

**Javascript errors shown in the web inspector (if applicable):**

```
no errors
```

**Additional information:**

**Comment by MindFreeze** [comment]
Yep. That looks like a bug

**Comment by icefest** [comment]
Whilst testing I also came upon this related bug:

**Whilst passthrough is enabled between _remaining_child_state_ and a downstream item it breaks the calculation of the remaining child state.**

Using the prior testbed, _remaining_child_state_ is reset to the full value of the child state. 

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/24628745/0607973d-6f59-41d2-b991-753705fe3fd2)

```
height: 800
unit_prefix: ''
round: 0
convert_units_to: ''
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_height: 3
min_box_distance: 5
show_states: true
show_units: true
sections:
  - entities:
      - type: entity
        children:
          - input_number.test_3
        entity_id: input_number.test_1
      - type: entity
        children:
          - input_number.test_3
          - remaining_parent
        entity_id: input_number.test_2
      - type: remaining_child_state
        children:
          - input_number.test_6
        entity_id: remaining_child
        name: Remaining Child
  - entities:
      - type: entity
        children:
          - input_number.test_4
        entity_id: input_number.test_3
      - type: remaining_parent_state
        children:
          - input_number.test_6
        entity_id: remaining_parent
        name: Remaining Parent
      - type: passthrough
        children:
          - input_number.test_6
        entity_id: input_number.test_6
  - entities:
      - type: entity
        children:
          - input_number.test_5
        entity_id: input_number.test_4
      - type: passthrough
        children:
          - input_number.test_6
        entity_id: input_number.test_6
  - entities:
      - type: entity
        children: []
        entity_id: input_number.test_5
      - type: entity
        children: []
        entity_id: input_number.test_6
type: custom:sankey-chart
show_names: true
title: Testing Enviroment
min_state: 0
```
