### ISSUE TITLE
v2.0.4 issue with missing childs

### ISSUE THREAD

**Issue by frittes** [MindFreeze/ha-sankey-chart#183]
After updating to 2.0.4 all my charts with passthrough are not working any more.

Example:

I have three sections with 

Left:
- solar
- grid
- battery

Middle:
- passthrough solar to grid
- remaining_parent_state solar to house
- passthrough grid to house/battery
- passthrough battery to house/grid

Right:
- house
- grid
- battery

Section config

```
    sections:
      - entities:
          - entity_id: sensor.senec_solar_generated_power
            color: '#FFB732'
            name: Photovoltaik
            children:
              - sensor.template_senec_to_grid
              - sensor.template_senec_to_battery
              - dummy
          - entity_id: sensor.template_senec_from_grid
            color: '#D06568'
            name: Netz
            children:
              - sensor.template_senec_from_grid
          - entity_id: sensor.template_senec_from_battery
            color: '#4CA64C'
            name: Speicher
            children:
              - sensor.template_senec_from_battery
      - entities:
          - entity_id: sensor.template_senec_to_grid
            type: passthrough
            color: '#4CA64C'
            children:
              - sensor.template_senec_to_grid
          - entity_id: dummy
            type: remaining_parent_state
            color: '#FFB732'
            children:
              - sensor.senec_house_power
          - entity_id: sensor.template_senec_from_grid
            type: passthrough
            color: '#D06568'
            children:
              - sensor.template_senec_to_battery
              - sensor.senec_house_power
          - entity_id: sensor.template_senec_from_battery
            type: passthrough
            color: '#4CA64C'
            children:
              - sensor.senec_house_power
              - sensor.template_senec_to_grid
      - entities:
          - entity_id: sensor.template_senec_to_grid
            color: '#4CA64C'
            name: Netz
          - entity_id: sensor.template_senec_to_battery
            color: '#4CA64C'
            name: Speicher
          - entity_id: sensor.senec_house_power
            color: '#4AB2E5'
            name: Haus
```

Error messages

`Error: Missing child entity sensor.template_senec_from_grid`
`Error: Missing child entity sensor.template_senec_from_battery`

If I add the missing entities to the third section it works, but they should not be shown there.

**Comment by MindFreeze** [comment]
Don't know what this showed before but this config is not supposed to work and the error is as intended.
Passthrough is supposed to have only 1 child that is the same as its entity_id. If you remove your passthroughs and let the card auto add them they will work

**Comment by frittes** [comment]
Thx for the quick reply. 👍 

Hmmm, this worked for round about a year. Going back to 2.0.3 and it works again.

I cannot show the chart, at the moment I have only grid to house. I´m a little bit confused, because this config worked for me. It was a bit tricky, but I solved it with the right order of the entities in the sections.

My battery always sends some watts to grid while discharging and I had a chart battery one flow to house and the other to grid (4th passthrough).

I will keep an eye on it.

**Comment by frittes** [comment]
This chart has the same errors.

Screenshot with 2.0.3

<img width="425" alt="Bildschirmfoto 2024-04-19 um 20 23 49" src="https://github.com/MindFreeze/ha-sankey-chart/assets/33233288/587e3bc9-8beb-4ee4-9ada-20dbb66aa199">

Config

```
        sections:
          - entities:
              - entity_id: sensor.generated_power_daily
                color: '#FFB732'
                name: Photovoltaik
                children:
                  - sensor.exported_power_daily
                  - sensor.power_to_battery_daily
                  - dummy
              - entity_id: sensor.imported_power_daily
                color: '#D06568'
                name: Netz
                children:
                  - sensor.imported_power_daily
              - entity_id: sensor.power_from_battery_daily
                color: '#4CA64C'
                name: Speicher
                children:
                  - sensor.power_from_battery_daily
          - entities:
              - entity_id: sensor.exported_power_daily
                type: passthrough
                color: '#4CA64C'
                children:
                  - sensor.exported_power_daily
              - entity_id: sensor.power_to_battery_daily
                type: passthrough
                color: '#FFB732'
                children:
                  - sensor.power_to_battery_daily
              - entity_id: dummy
                type: remaining_parent_state
                color: '#FFB732'
                children:
                  - sensor.power_hausverbrauch_daily
              - entity_id: sensor.imported_power_daily
                type: passthrough
                color: '#D06568'
                children:
                  - sensor.power_hausverbrauch_daily
              - entity_id: sensor.power_from_battery_daily
                type: passthrough
                color: '#4CA64C'
                children:
                  - sensor.power_hausverbrauch_daily
          - entities:
              - entity_id: sensor.exported_power_daily
                color: '#4CA64C'
                name: Netz
              - entity_id: sensor.power_to_battery_daily
                color: '#4CA64C'
                name: Speicher
              - entity_id: sensor.power_hausverbrauch_daily
                color: '#4AB2E5'
                name: Haus
```

**Comment by MindFreeze** [comment]
The way passthrough is intended to work is that you don't add the passthroughs yourself in most cases. The card will handle it and you only add explicit passthrough if you need to change the path or color of the connection.
I changed how it is calculated because it didn't work in many cases before where it should have. Seems like it did work for your case but that was unintended.

**Comment by MindFreeze** [comment]
your last config should work like this:

```
        sections:
          - entities:
              - entity_id: sensor.generated_power_daily
                color: '#FFB732'
                name: Photovoltaik
                children:
                  - sensor.exported_power_daily
                  - sensor.power_to_battery_daily
                  - sensor.power_hausverbrauch_daily
              - entity_id: sensor.imported_power_daily
                color: '#D06568'
                name: Netz
                children:
                  - sensor.power_hausverbrauch_daily
              - entity_id: sensor.power_from_battery_daily
                color: '#4CA64C'
                name: Speicher
                children:
                  - sensor.power_hausverbrauch_daily
          - entities:
              - entity_id: sensor.exported_power_daily
                type: passthrough
                color: '#4CA64C'
                children:
                  - sensor.exported_power_daily
              - entity_id: sensor.power_to_battery_daily
                type: passthrough
                color: '#FFB732'
                children:
                  - sensor.power_to_battery_daily
              - entity_id: sensor.power_hausverbrauch_daily
                type: passthrough
                children:
                  - sensor.power_hausverbrauch_daily
          - entities:
              - entity_id: sensor.exported_power_daily
                color: '#4CA64C'
                name: Netz
              - entity_id: sensor.power_to_battery_daily
                color: '#4CA64C'
                name: Speicher
              - entity_id: sensor.power_hausverbrauch_daily
                color: '#4AB2E5'
                name: Haus
```
