### ISSUE TITLE
Large padding at bottom

### ISSUE THREAD

**Issue by jelmerwouters** [MindFreeze/ha-sankey-chart#209]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v.3.2.2
**Last working release (if known):**
unknown
**Browser and Operating System:**
HA Core 2024.7.2
HA OS 12.4
HA Frontend 20240710.0
iOS 17.5.1

**Description of problem:**
At the bottom of the card there remains an unnecessary large padding. 
![B7F05296-A2D8-453C-B1ED-D04C0962AD4E_1_102_o](https://github.com/user-attachments/assets/74587397-7d0f-437c-b45c-8ae95f445f11)

YAML:
```yaml
type: custom:sankey-chart
energy_date_selection: true
show_names: true
wide: false
min_state: 0.01
sort_by: none
sort_dir: ''
show_icons: false
layout: vertical
height: 200
unit_prefix: k
round: 1
convert_units_to: ''
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_size: 5
min_box_distance: 2
show_states: true
show_units: false
sections:
  - entities:
      - type: entity
        children:
          - sensor.p1_meter_energy_export
          - verbruik
        entity_id: sensor.solax_yieldtoday
        name: Solar
        color: var(--energy-solar-color)
      - type: entity
        children:
          - sensor.p1_meter_energy_export
          - verbruik
        entity_id: sensor.p1_meter_energy_import_tariff_1
        name: Import Dal
        color: var(--energy-grid-consumption-color)
      - type: entity
        children:
          - sensor.p1_meter_energy_export
          - verbruik
        name: Import Normaal
        entity_id: sensor.p1_meter_energy_import_tariff_2
        color: var(--energy-grid-consumption-color)
  - entities:
      - type: entity
        children: []
        entity_id: sensor.p1_meter_energy_export
        name: Export
        color: var(--energy-grid-return-color)
      - type: remaining_parent_state
        children:
          - sensor.shelly_energy_monitor_wasmachine_energy
          - sensor.shelly_energy_monitor_wasdroger_energy
          - sensor.shelly_energy_monitor_vloerverwarming_badkamer_energy
          - sensor.tv_meubel_relay_0_energy
          - sensor.wtw_relay_0_energy
          - sensor.usw_switch_relay_0_energy
          - sensor.werkplek_relay_0_energy
          - sensor.sonos_relay_0_energy
          - unknown
        name: Verbruik
        entity_id: verbruik
        color: green
  - entities:
      - type: entity
        children: []
        entity_id: sensor.shelly_energy_monitor_wasmachine_energy
        name: Wasmachine
        color: blue
      - type: entity
        children: []
        entity_id: sensor.shelly_energy_monitor_wasdroger_energy
        name: Wasdroger
        color: plum
      - type: entity
        children: []
        entity_id: sensor.shelly_energy_monitor_vloerverwarming_badkamer_energy
        name: Badkamer
      - type: entity
        children: []
        entity_id: sensor.tv_meubel_relay_0_energy
        name: TV Meubel
        color: rgb(255, 127, 0)
      - type: entity
        children: []
        entity_id: sensor.wtw_relay_0_energy
        name: WTW
        color: rgb(176, 141, 0)
      - type: entity
        children: []
        entity_id: sensor.usw_switch_relay_0_energy
        name: USW Switch
      - type: entity
        children: []
        entity_id: sensor.werkplek_relay_0_energy
        name: Werkplek
      - type: entity
        children: []
        entity_id: sensor.sonos_relay_0_energy
        name: Sonos
      - type: remaining_parent_state
        children: []
        entity_id: unknown
        name: Overig
        color: lightskyblue
```

Changing layout, height, wide has no effect

**Javascript errors shown in the web inspector (if applicable):**
None

**Additional information:**
None
