### ISSUE TITLE
Entity Helper Not Showing Up

### ISSUE THREAD

**Issue by npotternyc** [MindFreeze/ha-sankey-chart#212]
**Checklist:**

- [x ] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
3.2.3

**Last working release (if known):**
NA
**Browser and Operating System:**
Chrome 127.0.6533.72 /MacOS
Same behavior using Safari

**Description of problem:**
I am adding a new entity and it is not showing up. That state and attribute information all look correct in developer tool:

```
state: 0.521
state_class: total_increasing 
status: collecting 
last_period: 0.855 
last_valid_state: 2.286 
last_reset: 2024-08-17T04:00:01.660769+00:00 
next_reset: 2024-08-18T00:00:00-04:00 
unit_of_measurement: kWh 
device_class: energy 
icon: mdi:lightning-bolt 
friendly_name: Basement Refrigerator Electric Consumption Daily
```

I have several other daily kWh helpers that are working fine in the sankey chart

**Javascript errors shown in the web inspector (if applicable):**
N/A

Full Config: 

```
layout: auto
height: 300
round: 1
min_box_size: 1
min_box_distance: 2
show_states: true
show_units: true
sections:
  - entities:
      - type: entity
        children:
          - sensor.solark_daily_battery_charge_energy
          - consumption
        entity_id: sensor.solark_daily_grid_buy_energy
        name: Generator
      - type: entity
        children:
          - sensor.solark_daily_battery_charge_energy
          - consumption
        entity_id: sensor.solark_daily_pv_energy
        name: Solar
        color: var(--warning-color)
      - type: entity
        children:
          - consumption
        entity_id: sensor.solark_daily_battery_discharge_energy
        name: Battery Output
        color: var(--success-color)
  - entities:
      - type: entity
        children: []
        entity_id: sensor.solark_daily_battery_charge_energy
        name: Battery Input
        color: var(--success-color)
      - type: remaining_parent_state
        children:
          - sensor.hot_water_heater_electric_consumption_kwh
          - sensor.refrigerator_daily_kwh
          - sensor.basement_refrigerator_electric_consumption_daily_kwh
          - sensor.home_assistant_today_s_consumption_2
          - sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_2_2
          - sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_2
          - sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_3
          - sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_4
          - sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_5
          - sensor.car_charge_outlet_electric_consumption_kwh
          - sensor.internal_heat_wire_energy_use_today
          - sensor.battery_charger_electric_consumption_kwh
          - other
        name: Consumption
        entity_id: consumption
  - entities:
      - type: entity
        children: []
        name: Basement Refrigerator
        entity_id: sensor.basement_refrigerator_electric_consumption_daily_kwh
      - type: entity
        children: []
        entity_id: sensor.hot_water_heater_electric_consumption_kwh
      - type: entity
        children: []
        name: Kitchen Refrigerator
        entity_id: sensor.refrigerator_daily_kwh
      - type: entity
        children: []
        entity_id: sensor.home_assistant_today_s_consumption_2
      - type: entity
        children: []
        entity_id: sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_2_2
      - type: entity
        children: []
        entity_id: sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_2
      - type: entity
        children: []
        entity_id: sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_3
      - type: entity
        children: []
        entity_id: sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_4
      - type: entity
        children: []
        entity_id: sensor.z_wave_plus_power_strip_ver_2_0_electric_consumption_kwh_5
      - type: entity
        children: []
        entity_id: sensor.car_charge_outlet_electric_consumption_kwh
      - type: entity
        children: []
        entity_id: sensor.internal_heat_wire_energy_use_today
        name: Heat Wires
      - type: entity
        children: []
        entity_id: sensor.battery_charger_electric_consumption_kwh
        name: Battery Charger
      - type: remaining_parent_state
        children: []
        entity_id: other
        name: Other Consumption
type: custom:sankey-chart
title: Energy Today
show_names: true
energy_date_selection: true
min_state: 0
throttle: 1000
min_box_height: 20
```
