### ISSUE TITLE
0.000000000000001 Discrepancy 

### ISSUE THREAD

**Issue by kzajac83** [MindFreeze/ha-sankey-chart#216]
Hello. 

Have the same sum of value childrens  vs parent = 868 liters (0.868 m3) but there is some discrepancy almost zero. UoM is of entities are "m3" so why more than 3 digits discrepancy? 

![image](https://github.com/user-attachments/assets/e73c51d8-e675-48df-959d-92370d3f1927)

![image](https://github.com/user-attachments/assets/3227171c-2564-4137-a6d0-74f6fc8fb32a)

```
layout: horizontal
height: 500
unit_prefix: ''
round: 3
convert_units_to: ''
min_box_size: 10
min_box_distance: 6
show_states: true
show_units: true
sections:
  - entities:
      - entity_id: sensor.adapr_na_1_licznik_glowny
        type: remaining_child_state
        childern: []
        name: Discrepancy1
        color: red
        children:
          - sensor.1_zw
          - sensor.2_zw
          - sensor.2_cwu
          - sensor.3_zw
          - sensor.3_cwu
          - sensor.4_zw
          - sensor.4_cwu
          - sensor.5_zw
          - sensor.5_cwu
          - sensor.6_zw
          - sensor.7_zw
          - sensor.7_cwu
          - sensor.8_zw
          - sensor.8_cwu
          - sensor.9_zw
          - sensor.9_cwu
          - sensor.10_zw
          - sensor.10_cwu
          - sensor.11_zw
          - sensor.11_cwu
          - sensor.12_zw
          - sensor.12_cwu
          - sensor.12a_zw
          - sensor.12a_cwu
          - sensor.adm_cwu
          - sensor.adm_zw
      - entity_id: sensor.adapr_na_1_licznik_glowny
        type: entity
        color_on_state: true
        name: Main water meter
        icon: mdi:account
        children:
          - sensor.1_zw
          - sensor.2_zw
          - sensor.2_cwu
          - sensor.3_zw
          - sensor.3_cwu
          - sensor.4_zw
          - sensor.4_cwu
          - sensor.5_zw
          - sensor.5_cwu
          - sensor.6_zw
          - sensor.7_zw
          - sensor.7_cwu
          - sensor.8_zw
          - sensor.8_cwu
          - sensor.9_zw
          - sensor.9_cwu
          - sensor.10_zw
          - sensor.10_cwu
          - sensor.11_zw
          - sensor.11_cwu
          - sensor.12_zw
          - sensor.12_cwu
          - sensor.12a_zw
          - sensor.12a_cwu
          - sensor.adm_cwu
          - sensor.adm_zw
  - entities:
      - type: entity
        children: []
        entity_id: sensor.1_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.2_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.2_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.3_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.3_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.4_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.4_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.5_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.5_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.6_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.7_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.7_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.8_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.8_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.9_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.9_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.10_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.10_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.11_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.11_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.12_zw
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.12_cwu
        unit_of_measurement: l
        convert_units_to: l
      - type: entity
        children: []
        entity_id: sensor.12a_zw
        unit_of_measurement: l
      - type: entity
        children: []
        entity_id: sensor.12a_cwu
        unit_of_measurement: l
      - type: entity
        children: []
        entity_id: sensor.adm_zw
        unit_of_measurement: l
      - type: entity
        children: []
        entity_id: sensor.adm_cwu
        unit_of_measurement: l
        convert_units_to: l
type: custom:sankey-chart
energy_date_selection: true
min_state: 0
show_names: true
show_icons: false
title: Wodociągi
wide: true
sort_by: state
```

PS. The same with with commented  all `unit_of_measurement: l`   and `convert_units_to: l` too:

![image](https://github.com/user-attachments/assets/77994b84-cbf9-4e64-b1b1-201e5cec1f58)
