### ISSUE TITLE
Missing child entity

### ISSUE THREAD

**Issue by Kedryn** [MindFreeze/ha-sankey-chart#227]
- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

```

      - entities:
          - entity_id: sensor.shelly_shem_485519d70cf0_2_total_consumption
            name: Appartamento
            type: entity
            color: purple
            children:
              - entity_id: sensor.scrivania_lory_power_energy_spent
              - entity_id: sensor.zswtelevisione_energy
              - entity_id: sensor.scrivania_manu_energy
              - entity_id: sensor.lavatrice_energy_spent
              - entity_id: sensor.frigorifero_consumo
              - entity_id: rimanenza_appartamento
                type: remaining_parent_state
                name: Altro
```
I would like to have, with this entity, all those meters plus an "Altro" (other) with the remaining unmetered power, as per documentation
but i get a "Error: Missing child entity rimanenza_appartamento"

In the example in docs, it states:
```

- entity_id: whatever # as long as it is unique
  type: remaining_parent_state
  name: Other
  
```
  
What i'm doing wrong?
