### ISSUE TITLE
Invert entity value

### ISSUE THREAD

**Issue by davidrapan** [MindFreeze/ha-sankey-chart#229]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would like to invert entity value directly in the card configuration without the need to create new sensor which is inverted. E.g. when configuring entities for consuming/returning power from/to the grid or battery.

**Describe alternatives you've considered**
I did create sensors which inverts the value but creating sensors just for this single purpose seems unreasonable to me.

**Additional context**
Currently I have to do this (notice the sensors with `_inverted` suffix):
```
sections:
  - entities:
      - type: entity
        children:
          - sensor.sankey_total_consumption
          - sensor.inverter_battery_power_inverted
        name: Grid
        entity_id: sensor.inverter_grid_power
      - type: entity
        children:
          - sensor.sankey_total_consumption
          - sensor.inverter_battery_power_inverted
          - sensor.inverter_grid_power_inverted
        name: Solar
        color: orange
        entity_id: sensor.inverter_pv_power
      - type: entity
        children:
          - sensor.sankey_total_consumption
          - sensor.inverter_grid_power_inverted
        name: Battery
        color: '#5fb6ad'
        entity_id: sensor.inverter_battery_power
  - entities:
      - type: entity
        children: []
        name: Grid Export
        color: '#a280db'
        entity_id: sensor.inverter_grid_power_inverted
      - type: entity
        children: []
        name: Battery
        color: '#f06292'
        entity_id: sensor.inverter_battery_power_inverted
      - type: remaining_parent_state
        children:
          - sensor.sankey_known_power
          - sensor.sankey_rest_of_the_power
        name: Consumption
        entity_id: sensor.sankey_total_consumption
        tap_action:
          action: none
```

**And would like to just use the original sensor and tell the sankey to invert the value for that particular case.**
