### ISSUE TITLE
Utility Meter values not rendered

### ISSUE THREAD

**Issue by Ashthos** [MindFreeze/ha-sankey-chart#239]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 3.5.0

**Last working release (if known):** Unknown

**Browser and Operating System:** Firefox / Chrome in Windows, Android Companion App

**Description of problem:**

Referencing a Utility meter with a tariff defined value is seemingly ignored by the Graph.

Adding the following yaml results in no values

```
height: 300
unit_prefix: k
round: 1
convert_units_to: ''
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 66.6
min_box_size: 3
min_box_distance: 5
show_states: true
show_units: true
energy_date_selection: true
sections:
  - entities:
      - entity_id: sensor.grid_consumption_today_tariff_offpeak
        name: Grid Offpeak
        type: entity
        children:
          - sensor.load_energy_today      
  - entities:      
      - entity_id: sensor.load_energy_today
        name: House Load
        type: entity
        children: []
    sort_by: state
    sort_group_by_parent: true
min_box_height: 3
type: custom:sankey-chart
min_state: 0
show_names: true
show_icons: false
wide: false
```

![image](https://github.com/user-attachments/assets/50e0a16b-d54b-4e1e-a41d-c6339a0b08a8)

In Developer Tools - you can see that the Utility Meter tariff sensor that is referenced has a state value that should result in something being rendered.

![image](https://github.com/user-attachments/assets/d10057d1-3c29-4eb5-8e9e-38bb968e274d)

**Additional information:**

These utility meters are historic, in that they have been defined in HA for well over a year. So there isn't an issue with the data taking a while to populate.
