### ISSUE TITLE
Entity more info pop-up no longer available

### ISSUE THREAD

**Issue by tomlut** [MindFreeze/ha-sankey-chart#24]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
0.6.4
**Last working release (if known):**

**Browser and Operating System:**
Firefox 93.0 Windows 10
Safari (HA Companion App), iOS 15.5

**Description of problem:**

I can no longer click on entity names in the Sankey graph to get the more info pop-up for the entity.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by MindFreeze** [comment]
I works fine here and there haven't been any changes that would cause this. Do you use card-mod or something similar that might be altering the card?

**Comment by tomlut** [comment]
Just tested in Chrome and that does not produce the pop-ups either. 

I'm connecting via Nabu Casa at the moment. I'll check if it works locally in 30 minutes or so. 

Tested using just the straight card config:
```
type: custom:sankey-chart
show_names: true
height: 300
round: 2
unit_prefix: k
wide: true
sections:
  - entities:
      - entity_id: sensor.grid_power
        name: Solar Power
        color: '#e0b400'
        children:
          - sensor.metering_power_supplied
          - sensor.solar_power_consumed
  - entities:
      - entity_id: sensor.solar_power_consumed
        name: Solar Power Consumption
        color: '#e0b400'
        children:
          - sensor.total_power_consumed
      - entity_id: sensor.metering_power_supplied
        name: Solar Power to Grid
        color: '#8353d1'
      - entity_id: sensor.metering_power_absorbed
        name: Grid Power Consumption
        children:
          - sensor.total_power_consumed
        color: '#e45e65'
  - entities:
      - entity_id: sensor.total_power_consumed
        name: Total Power Consumption
        remaining:
          name: Unmonitored
        children:
          - sensor.known_loads
        color: '#ff8000'
  - entities:
      - entity_id: sensor.known_loads
        name: Monitored Loads
        children:
          - sensor.bar_fridge_power
          - sensor.cinema_av_power
          - sensor.cinema_subwoofer_power
          - sensor.comms_rack_power
          - sensor.dishwasher_power
          - sensor.downstairs_heat_pump_power
          - sensor.electric_blanket_power
          - sensor.electronics_bench_power
          - sensor.fridge_power
          - sensor.hot_water_power
          - sensor.led_table_power
          - sensor.lounge_av_power
          - sensor.lounge_dehumidifier_power
          - sensor.mechanical_bench_power
          - sensor.pc_monitor_power
          - sensor.pi3b_power
          - sensor.rack_fan_power
          - sensor.rumpus_dehumidifier_power
          - sensor.spb_electric_blanket_power
          - sensor.upstairs_heat_pump_power
          - sensor.washing_machine_power
        color: '#039BE5'
  - entities:
      - sensor.bar_fridge_power
      - sensor.cinema_av_power
      - sensor.cinema_subwoofer_power
      - sensor.comms_rack_power
      - sensor.dishwasher_power
      - sensor.downstairs_heat_pump_power
      - sensor.electric_blanket_power
      - sensor.electronics_bench_power
      - sensor.fridge_power
      - sensor.hot_water_power
      - sensor.led_table_power
      - sensor.lounge_av_power
      - sensor.lounge_dehumidifier_power
      - sensor.mechanical_bench_power
      - sensor.pc_monitor_power
      - sensor.pi3b_power
      - sensor.rack_fan_power
      - sensor.rumpus_dehumidifier_power
      - sensor.spb_electric_blanket_power
      - sensor.upstairs_heat_pump_power
      - sensor.washing_machine_power
```
