### ISSUE TITLE
Remaining, not clear how to use

### ISSUE THREAD

**Issue by kzajac83** [MindFreeze/ha-sankey-chart#244]
Hello.

Hope this is not a bug but just wrong implement config however I spent whole evening trying implement below both codes and total zero success. 
```
- entity_id: whatever # as long as it is unique
  type: remaining_child_state
  name: Discrepancy
```
or 
```
- entity_id: whatever # as long as it is unique
  type: remaining_parent_state
  name: Other
```

My 1st section is water meter from water supply company, middle section is subtotal water meter for how water (before boiling room) only and right section is end water meters for hot and cold water. Sometimes on end of day sum left vs right is zero, sometime on plus and sometime on minus.  But discrepences on plus or minus cannot visualization :/
Can I get help?

![image](https://github.com/user-attachments/assets/055f64e1-fd6c-4955-b91a-6661f29f5419)

My code is

```
layout: horizontal
height: 400
unit_prefix: ""
round: 3
convert_units_to: ""
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_size: 6
min_box_distance: 7
show_states: true
show_units: true
sections:
  - entities:
      - type: remaining_child_state
        entity_id: iiuiugig9iuiubiubiubi
        name: Discrepancy
      - type: entity
        children:
          - sensor.wmbus_reader_v2_wezel_zw_do_cwu_wifi_total
          - sensor.1_zw
          - sensor.2_zw
          - sensor.3_zw
          - sensor.4_zw
          - sensor.5_zw
          - sensor.6_zw
          - sensor.7_zw
          - sensor.8_zw
          - sensor.9_zw
          - sensor.10_zw
          - sensor.11_zw
          - sensor.12_zw
          - sensor.12a_zw
          - sensor.adm_zw
        entity_id: sensor.wmbus_reader_v2_apator_wifi_na_1_total
        color: blue
        color_on_state: false
        remaining_child_state: 1
  - entities:
      - type: entity
        children:
          - sensor.cwu_1_total_volume_m3
          - sensor.cwu_2_total_volume_m3
          - sensor.cwu_3_total_volume_m3
          - sensor.cwu_4_total_volume_m3
          - sensor.cwu_5_total_volume_m3
          - sensor.cwu_7_total_volume_m3
          - sensor.cwu_8_total_volume_m3
          - sensor.cwu_9_total_volume_m3
          - sensor.cwu_10_total_volume_m3
          - sensor.cwu_11_total_volume_m3
          - sensor.cwu_12_total_volume_m3
          - sensor.cwu_12a_total_volume_m3
          - sensor.cwu_adm_total_volume_m3
        entity_id: sensor.wmbus_reader_v2_wezel_zw_do_cwu_wifi_total
        color: red
      - type: passthrough
        children: []
        entity_id: sensor.1_zw
      - type: passthrough
        children: []
        entity_id: sensor.2_zw
      - type: passthrough
        children: []
        entity_id: sensor.3_zw
      - type: passthrough
        children: []
        entity_id: sensor.4_zw
      - type: passthrough
        children: []
        entity_id: sensor.5_zw
      - type: passthrough
        children: []
        entity_id: sensor.6_zw
      - type: passthrough
        children: []
        entity_id: sensor.7_zw
      - type: passthrough
        children: []
        entity_id: sensor.8_zw
      - type: passthrough
        children: []
        entity_id: sensor.9_zw
      - type: passthrough
        children: []
        entity_id: sensor.10_zw
      - type: passthrough
        children: []
        entity_id: sensor.11_zw
      - type: passthrough
        children: []
        entity_id: sensor.12_zw
      - type: passthrough
        children: []
        entity_id: sensor.12a_zw
      - type: passthrough
        children: []
        entity_id: sensor.adm_zw
  - entities:
      - type: entity
        children: []
        entity_id: sensor.cwu_1_total_volume_m3
        color: DarkSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_2_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_3_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_4_total_volume_m3
        color: IndianRed
      - type: entity
        children: []
        entity_id: sensor.cwu_5_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_7_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_8_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_9_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_10_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_11_total_volume_m3
        color: Salmon
      - type: entity
        children: []
        entity_id: sensor.cwu_12_total_volume_m3
        color: LightCoral
      - type: entity
        children: []
        entity_id: sensor.cwu_12a_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_adm_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.1_zw
      - type: entity
        children: []
        entity_id: sensor.2_zw
      - type: entity
        children: []
        entity_id: sensor.3_zw
      - type: remaining_child_state
        children: []
        entity_id: sensor.4_zw
      - type: entity
        children: []
        entity_id: sensor.5_zw
      - type: entity
        children: []
        entity_id: sensor.6_zw
      - type: entity
        children: []
        entity_id: sensor.7_zw
      - type: entity
        children: []
        entity_id: sensor.8_zw
      - type: entity
        children: []
        entity_id: sensor.9_zw
      - type: entity
        children: []
        entity_id: sensor.10_zw
      - type: entity
        children: []
        entity_id: sensor.11_zw
      - type: entity
        children: []
        entity_id: sensor.12_zw
      - type: entity
        children: []
        entity_id: sensor.12a_zw
      - type: entity
        children: []
        entity_id: sensor.adm_zw
      - entity_id: whatepopojpver # as long as it is unique
        type: remaining_child_state
        name: Other
type: custom:sankey-chart
title: Sankey wodociągi
energy_date_selection: true
show_names: true
show_icons: false
sort_dir: desc
wide: true
sort_by: state

```

**Comment by MindFreeze** [comment]
You are using `remaining_child_state` without any children. How should the card know which entities to link it to?
Similarly, if you want to use `remaining_parent_state`, it must be listed in `children` of the relevant entities.

**Comment by kzajac83** [comment]
Ehhh, this is reason why asking, not understood how implement both :(
Now I change into this but disappear little visualization (missing extra quantity not counted) but not appear any new value. Can you help please more preciously? 


```
layout: horizontal
height: 400
unit_prefix: ""
round: 3
convert_units_to: ""
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_size: 6
min_box_distance: 7
show_states: true
show_units: true
sections:
  - entities:
      - type: remaining_child_state
        name: Input
        children:
          - sensor.wmbus_reader_v2_wezel_zw_do_cwu_wifi_total
          - sensor.1_zw
          - sensor.2_zw
          - sensor.3_zw
          - sensor.4_zw
          - sensor.5_zw
          - sensor.6_zw
          - sensor.7_zw
          - sensor.8_zw
          - sensor.9_zw
          - sensor.10_zw
          - sensor.11_zw
          - sensor.12_zw
          - sensor.12a_zw
          - sensor.adm_zw
        entity_id: sensor.wmbus_reader_v2_apator_wifi_na_1_total
        color: blue
        color_on_state: false
        remaining_child_state: 1
  - entities:
      - type: entity
        children:
          - sensor.cwu_1_total_volume_m3
          - sensor.cwu_2_total_volume_m3
          - sensor.cwu_3_total_volume_m3
          - sensor.cwu_4_total_volume_m3
          - sensor.cwu_5_total_volume_m3
          - sensor.cwu_7_total_volume_m3
          - sensor.cwu_8_total_volume_m3
          - sensor.cwu_9_total_volume_m3
          - sensor.cwu_10_total_volume_m3
          - sensor.cwu_11_total_volume_m3
          - sensor.cwu_12_total_volume_m3
          - sensor.cwu_12a_total_volume_m3
          - sensor.cwu_adm_total_volume_m3
        entity_id: sensor.wmbus_reader_v2_wezel_zw_do_cwu_wifi_total
        color: red
      - type: passthrough
        children: []
        entity_id: sensor.1_zw
      - type: passthrough
        children: []
        entity_id: sensor.2_zw
      - type: passthrough
        children: []
        entity_id: sensor.3_zw
      - type: passthrough
        children: []
        entity_id: sensor.4_zw
      - type: passthrough
        children: []
        entity_id: sensor.5_zw
      - type: passthrough
        children: []
        entity_id: sensor.6_zw
      - type: passthrough
        children: []
        entity_id: sensor.7_zw
      - type: passthrough
        children: []
        entity_id: sensor.8_zw
      - type: passthrough
        children: []
        entity_id: sensor.9_zw
      - type: passthrough
        children: []
        entity_id: sensor.10_zw
      - type: passthrough
        children: []
        entity_id: sensor.11_zw
      - type: passthrough
        children: []
        entity_id: sensor.12_zw
      - type: passthrough
        children: []
        entity_id: sensor.12a_zw
      - type: passthrough
        children: []
        entity_id: sensor.adm_zw
  - entities:
      - type: entity
        children: []
        entity_id: sensor.cwu_1_total_volume_m3
        color: DarkSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_2_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_3_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_4_total_volume_m3
        color: IndianRed
      - type: entity
        children: []
        entity_id: sensor.cwu_5_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_7_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_8_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_9_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_10_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_11_total_volume_m3
        color: Salmon
      - type: entity
        children: []
        entity_id: sensor.cwu_12_total_volume_m3
        color: LightCoral
      - type: entity
        children: []
        entity_id: sensor.cwu_12a_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_adm_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.1_zw
      - type: entity
        children: []
        entity_id: sensor.2_zw
      - type: entity
        children: []
        entity_id: sensor.3_zw
      - type: entity
        children: []
        entity_id: sensor.4_zw
      - type: entity
        children: []
        entity_id: sensor.5_zw
      - type: entity
        children: []
        entity_id: sensor.6_zw
      - type: entity
        children: []
        entity_id: sensor.7_zw
      - type: entity
        children: []
        entity_id: sensor.8_zw
      - type: entity
        children: []
        entity_id: sensor.9_zw
      - type: entity
        children: []
        entity_id: sensor.10_zw
      - type: entity
        children: []
        entity_id: sensor.11_zw
      - type: entity
        children: []
        entity_id: sensor.12_zw
      - type: entity
        children: []
        entity_id: sensor.12a_zw
      - type: entity
        children: []
        entity_id: sensor.adm_zw
      - type: remaining_child_state
        name: Other
        entity_id: sensor.wmbus_reader_v2_apator_wifi_na_1_total
type: custom:sankey-chart
title: Sankey wodociągi
energy_date_selection: true
show_names: true
show_icons: false
sort_dir: desc
wide: true
sort_by: state

```
