### ISSUE TITLE
Remaining of children or parent + type: passthrough = wrong calculations

### ISSUE THREAD

**Issue by kzajac83** [MindFreeze/ha-sankey-chart#246]
Hello

I see discrepancy for parent and children calculation longer time but cannot show ease as now due to many entities in graphs. 
The issue is related to calculations of remaining parent.children probably where is used `type: passthrough` because only this chart i found I issue wrong calculated discrepancy. 

My Sankey displaying square meters of water, where one liter is is equal 1/1000 of m3. Left site of picture is main water supply and right site is end water meters.  Between is sub water meter for boiling room. I build two Sankey graphs with and without middle section with sub water meter. And unfortunately both graphs always calculate difference values of remaining of children or parent. 

For the period (from 0:00 to 1:00) is only two liters (0.002 m3) consumed.  

![image](https://github.com/user-attachments/assets/e84ef943-2b19-48e7-bff3-270784a1e2ae)

![image](https://github.com/user-attachments/assets/aafb1d92-055e-434d-a465-12404d3e46f9)

I will show two examples, correct and wrong.

**Correct example**

8 liter =  6 liter + 1 liter + 1 liter ==> TRUE

![image](https://github.com/user-attachments/assets/e32cc26a-14e3-456d-9272-17016f1d5863)

```
layout: horizontal
height: 400
unit_prefix: ""
round: 4
convert_units_to: ""
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_size: 6
min_box_distance: 7
show_states: true
show_units: true
sections:
  - entities:
      - type: remaining_child_state
        children:
          - sensor.cwu_1_total_volume_m3
          - sensor.cwu_2_total_volume_m3
          - sensor.cwu_3_total_volume_m3
          - sensor.cwu_4_total_volume_m3
          - sensor.cwu_5_total_volume_m3
          - sensor.cwu_7_total_volume_m3
          - sensor.cwu_8_total_volume_m3
          - sensor.cwu_9_total_volume_m3
          - sensor.cwu_10_total_volume_m3
          - sensor.cwu_11_total_volume_m3
          - sensor.cwu_12_total_volume_m3
          - sensor.cwu_12a_total_volume_m3
          - sensor.cwu_adm_total_volume_m3
          - sensor.1_zw
          - sensor.2_zw
          - sensor.3_zw
          - sensor.4_zw
          - sensor.5_zw
          - sensor.6_zw
          - sensor.7_zw
          - sensor.8_zw
          - sensor.9_zw
          - sensor.10_zw
          - sensor.11_zw
          - sensor.12_zw
          - sensor.12a_zw
          - sensor.adm_zw
        entity_id: whatever
        name: Discrepancy
        color: green
      - type: entity
        children:
          - sensor.cwu_1_total_volume_m3
          - sensor.cwu_2_total_volume_m3
          - sensor.cwu_3_total_volume_m3
          - sensor.cwu_4_total_volume_m3
          - sensor.cwu_5_total_volume_m3
          - sensor.cwu_7_total_volume_m3
          - sensor.cwu_8_total_volume_m3
          - sensor.cwu_9_total_volume_m3
          - sensor.cwu_10_total_volume_m3
          - sensor.cwu_11_total_volume_m3
          - sensor.cwu_12_total_volume_m3
          - sensor.cwu_12a_total_volume_m3
          - sensor.cwu_adm_total_volume_m3
          - sensor.1_zw
          - sensor.2_zw
          - sensor.3_zw
          - sensor.4_zw
          - sensor.5_zw
          - sensor.6_zw
          - sensor.7_zw
          - sensor.8_zw
          - sensor.9_zw
          - sensor.10_zw
          - sensor.11_zw
          - sensor.12_zw
          - sensor.12a_zw
          - sensor.adm_zw
          - reszta
        name: Input
        entity_id: sensor.wmbus_reader_v2_apator_wifi_na_1_total
        color: blue
        color_on_state: false
  - entities:
      - type: entity
        children: []
        entity_id: sensor.cwu_1_total_volume_m3
        color: DarkSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_2_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_3_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_4_total_volume_m3
        color: IndianRed
      - type: entity
        children: []
        entity_id: sensor.cwu_5_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_7_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_8_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_9_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_10_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_11_total_volume_m3
        color: Salmon
      - type: entity
        children: []
        entity_id: sensor.cwu_12_total_volume_m3
        color: LightCoral
      - type: entity
        children: []
        entity_id: sensor.cwu_12a_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_adm_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.1_zw
      - type: entity
        children: []
        entity_id: sensor.2_zw
      - type: entity
        children: []
        entity_id: sensor.3_zw
      - type: entity
        children: []
        entity_id: sensor.4_zw
      - type: entity
        children: []
        entity_id: sensor.5_zw
      - type: entity
        children: []
        entity_id: sensor.6_zw
      - type: entity
        children: []
        entity_id: sensor.7_zw
      - type: entity
        children: []
        entity_id: sensor.8_zw
      - type: entity
        children: []
        entity_id: sensor.9_zw
      - type: entity
        children: []
        entity_id: sensor.10_zw
      - type: entity
        children: []
        entity_id: sensor.11_zw
      - type: entity
        children: []
        entity_id: sensor.12_zw
      - type: entity
        children: []
        entity_id: sensor.12a_zw
      - type: entity
        children: []
        entity_id: sensor.adm_zw
      - type: remaining_parent_state
        children: []
        name: reszta
        entity_id: reszta
        color: green
type: custom:sankey-chart
title: Sankey wodociągi
energy_date_selection: true
show_names: true
show_icons: false
sort_dir: desc
wide: true
sort_by: state
min_state: 0.0001

```

**Issue example** 

8 liters =/= 7 liters + 1 liter + 1 liter ==> FALSE

There is in middle entity related to  "sensor.wmbus_reader_v2_wezel_zw_do_cwu_wifi_total" but zero registered

![image](https://github.com/user-attachments/assets/e44d9abd-be1e-4696-9a4f-d45446c293e0)

```
layout: horizontal
height: 400
unit_prefix: ""
round: 4
convert_units_to: ""
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_size: 6
min_box_distance: 7
show_states: true
show_units: true
sections:
  - entities:
      - type: remaining_child_state
        children:
          - sensor.wmbus_reader_v2_wezel_zw_do_cwu_wifi_total
          - sensor.1_zw
          - sensor.2_zw
          - sensor.3_zw
          - sensor.4_zw
          - sensor.5_zw
          - sensor.6_zw
          - sensor.7_zw
          - sensor.8_zw
          - sensor.9_zw
          - sensor.10_zw
          - sensor.11_zw
          - sensor.12_zw
          - sensor.12a_zw
          - sensor.adm_zw
        entity_id: whatever
        name: Discrepancy
        color: green
      - type: entity
        children:
          - sensor.wmbus_reader_v2_wezel_zw_do_cwu_wifi_total
          - sensor.1_zw
          - sensor.2_zw
          - sensor.3_zw
          - sensor.4_zw
          - sensor.5_zw
          - sensor.6_zw
          - sensor.7_zw
          - sensor.8_zw
          - sensor.9_zw
          - sensor.10_zw
          - sensor.11_zw
          - sensor.12_zw
          - sensor.12a_zw
          - sensor.adm_zw
          - reszta
        name: Input
        entity_id: sensor.wmbus_reader_v2_apator_wifi_na_1_total
        color: blue
        color_on_state: false
  - entities:
      - type: entity
        children:
          - sensor.cwu_1_total_volume_m3
          - sensor.cwu_2_total_volume_m3
          - sensor.cwu_3_total_volume_m3
          - sensor.cwu_4_total_volume_m3
          - sensor.cwu_5_total_volume_m3
          - sensor.cwu_7_total_volume_m3
          - sensor.cwu_8_total_volume_m3
          - sensor.cwu_9_total_volume_m3
          - sensor.cwu_10_total_volume_m3
          - sensor.cwu_11_total_volume_m3
          - sensor.cwu_12_total_volume_m3
          - sensor.cwu_12a_total_volume_m3
          - sensor.cwu_adm_total_volume_m3
        entity_id: sensor.wmbus_reader_v2_wezel_zw_do_cwu_wifi_total
        color: red
      - type: passthrough
        children: []
        entity_id: sensor.1_zw
      - type: passthrough
        children: []
        entity_id: sensor.2_zw
      - type: passthrough
        children: []
        entity_id: sensor.3_zw
      - type: passthrough
        children: []
        entity_id: sensor.4_zw
      - type: passthrough
        children: []
        entity_id: sensor.5_zw
      - type: passthrough
        children: []
        entity_id: sensor.6_zw
      - type: passthrough
        children: []
        entity_id: sensor.7_zw
      - type: passthrough
        children: []
        entity_id: sensor.8_zw
      - type: passthrough
        children: []
        entity_id: sensor.9_zw
      - type: passthrough
        children: []
        entity_id: sensor.10_zw
      - type: passthrough
        children: []
        entity_id: sensor.11_zw
      - type: passthrough
        children: []
        entity_id: sensor.12_zw
      - type: passthrough
        children: []
        entity_id: sensor.12a_zw
      - type: passthrough
        children: []
        entity_id: sensor.adm_zw
      - type: passthrough
        children: []
        name: reszta
        entity_id: reszta
        color: green
  - entities:
      - type: entity
        children: []
        entity_id: sensor.cwu_1_total_volume_m3
        color: DarkSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_2_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_3_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_4_total_volume_m3
        color: IndianRed
      - type: entity
        children: []
        entity_id: sensor.cwu_5_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_7_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_8_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_9_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_10_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_11_total_volume_m3
        color: Salmon
      - type: entity
        children: []
        entity_id: sensor.cwu_12_total_volume_m3
        color: LightCoral
      - type: entity
        children: []
        entity_id: sensor.cwu_12a_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.cwu_adm_total_volume_m3
        color: LightSalmon
      - type: entity
        children: []
        entity_id: sensor.1_zw
      - type: entity
        children: []
        entity_id: sensor.2_zw
      - type: entity
        children: []
        entity_id: sensor.3_zw
      - type: entity
        children: []
        entity_id: sensor.4_zw
      - type: entity
        children: []
        entity_id: sensor.5_zw
      - type: entity
        children: []
        entity_id: sensor.6_zw
      - type: entity
        children: []
        entity_id: sensor.7_zw
      - type: entity
        children: []
        entity_id: sensor.8_zw
      - type: entity
        children: []
        entity_id: sensor.9_zw
      - type: entity
        children: []
        entity_id: sensor.10_zw
      - type: entity
        children: []
        entity_id: sensor.11_zw
      - type: entity
        children: []
        entity_id: sensor.12_zw
      - type: entity
        children: []
        entity_id: sensor.12a_zw
      - type: entity
        children: []
        entity_id: sensor.adm_zw
      - type: remaining_parent_state
        children: []
        name: reszta
        entity_id: reszta
        color: green
type: custom:sankey-chart
title: Sankey wodociągi
energy_date_selection: true
show_names: true
show_icons: false
sort_dir: desc
wide: true
sort_by: state
min_state: 0.0001

```

Example for the same yesterday period and please check "reszta" / remaining  value. Fiers with middle section, 2nd without middle section.

![image](https://github.com/user-attachments/assets/03ab70ff-56c4-4a91-b068-0ec723c6bbbe)

![image](https://github.com/user-attachments/assets/ac7c6d2c-f04f-454c-8311-eeb51ec55a1f)

Another day:

![image](https://github.com/user-attachments/assets/0edbe5b3-7a68-4586-a50d-de16398c8bdb)

![image](https://github.com/user-attachments/assets/e47c2ff6-a3b1-4bc6-b326-783fca2bd814)
