### ISSUE TITLE
allow custom name: for children (just like can be done for parents)

### ISSUE THREAD

**Issue by bob454522** [MindFreeze/ha-sankey-chart#249]
first off, wow!  thank you so much for your work on this sankey card and making it public!  i LOVE sankey graphs/charts, and your card has allowed me to make some beautiful and informative charts on my home power usage! (and very easily/quickly btw)!  (see my pict at the bottom, im still tweaking it).  I encourage anyone who makes use of this card to donate to mindfreeze (either via buy me coffee link, or github sponsor link).  (also btw-  using the grafana time range syntax is a great touch/idea!)

**Is your feature request related to a problem? Please describe.**
Would be great if we could manually set a custom name for the children of parents (just as we are able to with the parents, currently).

example of what i think would be helpful (the part under children:  allow user to optionally specify a name:  ) :
```
        sections:
          - entities:
              - entity_id: sensor.sum_bothmains_wh
                name: Entergy Feed Sum   < (this works / is allowed)
                color: var(--success-color)
                children:
                  - entity_id: sensor.ac_1stfl_50a_i9_wh
                    name: AC 1st Floor   < (this does NOT work , and is what im asking for in this feature request)
                  - entity_id: sensor.panel_1stfl_i7x2_wh
                    name: Panel 1st Floor
```

**Additional context**
currently the children of parents take their name from the Home assistant entity name,  which works great!  but sometimes is a bit more verbose than a user may want to display (or maybe wrong/outdated).

I'm aware a workaround is to make template sensors, however I think that's a bit overkill / additional complexity just to accomplish a rename.
thank you!

![image](https://github.com/user-attachments/assets/2315f86d-eaed-4b88-86d0-441eb373fa62)

here is the full yaml for the card above, If anyone's interested, I don't include the bottom navigation bar as it's not related to this sankey project).

```
    cards:
      - type: custom:sankey-chart
        energy_date_selection: false
        layout: auto
        height: 690
        unit_prefix: k
        time_period_from: now/d
        round: 1
        wide: true
        show_names: true
        sections:
          - entities:
              - entity_id: sensor.sum_bothmains_wh
                name: Entergy Feed Sum
                color: var(--success-color)
                children:
                  - sensor.ac_1stfl_50a_i9_wh
                  - sensor.panel_1stfl_i7x2_wh
                  - sensor.sum_bothgrgmains_wh
                  - sensor.in_50a_i8_wh
                  - sensor.unknown_50a_i5_wh
                  - sensor.workrm_quad_50a_4_wh
                  - sensor.yardlts_gfi_emp_i11_wh
          - entities:
              - sensor.ac_1stfl_50a_i9_wh
              - sensor.panel_1stfl_i7x2_wh
              - sensor.in_50a_i8_wh
              - sensor.unknown_50a_i5_wh
              - sensor.workrm_quad_50a_4_wh
              - sensor.yardlts_gfi_emp_i11_wh
          - entities:
              - entity_id: sensor.sum_bothgrgmains_wh
                name: Garage Panel
                color: var(--success-color)
                children:
                  - sensor.ac_2ndfl_x2_i12_wh
                  - sensor.rack_quad_x2_wh
                  - sensor.poolpump_x2_i6_wh
                  - sensor.ac_minisplit_tot_wh
                  - sensor.eeareaquad_i11_wh
                  - sensor.xx_i5_wh
                  - sensor.xx_i7_wh
          - entities:
              - sensor.ac_2ndfl_x2_i12_wh
              - sensor.rack_quad_x2_wh
              - sensor.poolpump_x2_i6_wh
              - sensor.ac_minisplit_tot_wh
              - sensor.eeareaquad_i11_wh
              - sensor.xx_i5_wh
              - sensor.xx_i7_wh

```

**Comment by bob454522** [comment]
pfff-  you actually can already do what im requesting here!  (so closing this).

the way you do it is under the entities (below the children:).  ie like this:

```
        sections:
          - entities:
              - entity_id: sensor.sum_bothmains_wh
                name: Entergy Feed Sum
                color: var(--success-color)
                children:
                  - sensor.ac_1stfl_50a_i9_wh
                  - sensor.panel_1stfl_i7x2_wh
                  - sensor.sum_bothgrgmains_wh
                  - sensor.in_50a_i8_wh
                  - sensor.unknown_50a_i5_wh
                  - sensor.workrm_quad_50a_4_wh
                  - sensor.yardlts_gfi_emp_i11_wh
          - entities:
              - entity_id: sensor.ac_1stfl_50a_i9_wh
                name: 1stFLac
              - entity_id: sensor.panel_1stfl_i7x2_wh
                name: Panel-1stFL
```

so forexample this child:
```               
               children:
                  - sensor.ac_1stfl_50a_i9_wh
```
gets renamed to my custom name via this yaml:
```
                children:
                   - sensor.ac_1stfl_50a_i9_wh
          - entities:
              - entity_id: sensor.ac_1stfl_50a_i9_wh
                name: 1stFLac
```
(and alot more options beyond name can be set too!)
