### ISSUE TITLE
Using time_period_from the diagram is blank / empty

### ISSUE THREAD

**Issue by orimate** [MindFreeze/ha-sankey-chart#263]
If` I add _time_period_from_ I see only a blank window. How can I it get to work?

`layout: horizontal
height: 90
unit_prefix: ""
round: 0
convert_units_to: ""
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_size: 3
min_box_distance: 5
show_states: true
show_units: false
sections:
  - entities:
      - type: entity
        children:
          - sensor.wlan_charge_w_noah2000_0
          - sensor.wlan_consumption_solar_0
        name: Solar
        entity_id: sensor.wlan_solar_w_noah2000_0
        color: "#ff8000"
      - type: entity
        children:
          - sensor.wlan_consumption_solar_0
        name: Batt-
        entity_id: sensor.wlan_discharge_w_noah2000_0
        color: "#ff0000"
  - entities:
      - type: entity
        children:
          - sensor.wlan_power_real_power_energy_meter_0
        name: Grid
        entity_id: sensor.wlan_power_real_imp_exp_energy_meter_0
        color: "#ffcc99"
      - type: entity
        children:
          - sensor.wlan_power_real_power_energy_meter_0
        name: Inverter
        entity_id: sensor.wlan_consumption_solar_0
        color: "#ff3399"
      - type: passthrough
        children: []
        color: "#00ff00"
        name: Batt+
        entity_id: sensor.wlan_charge_w_noah2000_0
  - entities:
      - type: entity
        children:
          - sensor.wlan_consumption_garden_0
        name: Home
        entity_id: sensor.wlan_power_real_power_energy_meter_0
      - type: entity
        children: []
        color: "#00ff00"
        name: Batt+
        entity_id: sensor.wlan_charge_w_noah2000_0
  - entities:
      - type: entity
        children:
          - sensor.wlan_consumption_shelly_pro_1pm_0
        name: Garden
        entity_id: sensor.wlan_consumption_garden_0
        color: "#8f3bb8"
  - entities:
      - type: entity
        children: []
        name: Niro
        entity_id: sensor.wlan_consumption_shelly_pro_1pm_0
        color: "#ffffff"
type: custom:sankey-chart
show_names: true
energy_date_selection: false
time_period_from: now-2h
grid_options:
  columns: 20
  rows: 2
show_icons: false
wide: false
min_state: 5`

**Comment by MindFreeze** [comment]
time_period_from is a global option, not a section option

**Comment by orimate** [comment]
Sorry, I did not checked my comment and somehow the tabs are wrong. I placed on top, so the code is now: Is still empty.

```
layout: horizontal
type: custom:sankey-chart
show_names: true
energy_date_selection: false
time_period_from: now-2h
grid_options:
  columns: 20
  rows: 2
show_icons: false
wide: false
min_state: 5
height: 90
unit_prefix: ""
round: 0
convert_units_to: ""
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_size: 3
```
.....
