### ISSUE TITLE
Support for Templating in Sankey chart yaml

### ISSUE THREAD

**Issue by arnaud-gouder** [MindFreeze/ha-sankey-chart#265]
Hi, thanks for your great work on this project!

I'm trying to find a way to automatically include all my Tasmota devices in a Sankey chart. Currently, I manage this manually using a Jinja2 template in the Home Assistant 'Developer Tools', and then copy-paste the output into the Sankey chart YAML.

Below is a simplified version of what I use.

The reason I want this to be automatic is that I occasionally replace or update devices, and it's easy to forget updating the chart. Ideally, I'd like to embed the template directly in the Sankey YAML, but this doesn’t seem to work.

So my questions are:

-     Am I doing something wrong, or is templating not supported in this context?
-     If not currently supported, could support for templating be added as a new feature?

Thanks again!

```
height: 800
unit_prefix: k
round: 1
min_box_height: 3
min_box_distance: 5
show_states: true
show_units: true
sections:
  - entities:
      - type: entity
        children:
          - total
        entity_id: sensor.electricity_meter_energy_consumption_tarif_1
        name: Usage
        add_entities:
          - sensor.electricity_meter_energy_consumption_tarif_2
      - type: entity
        children:
          - total
        entity_id: sensor.solaredge_lifetime_energy
        name: Solar
        color: orange
  - entities:
      - type: remaining_parent_state
        children:
          - sensor.electricity_meter_energy_production_tarif_1
          - unknown
      {%- for entity in (expand(integration_entities("tasmota")) |
         selectattr("attributes.device_class", "match", "energy") | 
         selectattr("attributes.state_class", "match", "total$") 
      %}
          - {{ entity.entity_id }} 
      {%- endfor %}
        entity_id: total
        name: Total Consumption
  - entities:
      - type: entity
        children: []
        entity_id: sensor.electricity_meter_energy_production_tarif_1
        name: Production
        add_entities:
          - sensor.electricity_meter_energy_production_tarif_2
        color: green
      - type: remaining_parent_state
        children: []
        entity_id: unknown
        name: Unknown
      {%- for entity in (expand(integration_entities("tasmota")) |
         selectattr("attributes.device_class", "match", "energy") | 
         selectattr("attributes.state_class", "match", "total$")
      %}
      - type: entity
        children: []
        entity_id: {{ entity.entity_id }} 
        name: {{ entity.attributes.friendly_name | replace(' ENERGY Total', "") }}
      {%- endfor %}
    sort_by: state
    sort_dir: asc
  - entities: []
type: custom:sankey-chart
min_state: 0
show_names: true
show_icons: false
energy_date_selection: true
wide: true
throttle: 0
```
