### ISSUE TITLE
add visibility option or direct entity_id in dynamic options

### ISSUE THREAD

**Issue by Mariusthvdb** [MindFreeze/ha-sankey-chart#269]
**Is your feature request related to a problem? Please describe.**

Currently we need the config-template-card, to have an input_select for eg sankey_min_state and dynamically change the display
```
type: custom:config-template-card
entities:
  - input_select.sankey_min_state
variables:
  min_state: states['input_select.sankey_min_state'].state
card:
  type: custom:sankey-chart
  title: Energie onderverdeling
  min_state: ${min_state}
etcetc
```

**Describe the solution you'd like**

Would be great if we could have support for the core option of visibility, so we can do something like:

```
type: vertical-stack
cards:
  - min_state: 0.1
    visibility:
      - condition: state
        entity_id: input_select.sankey_min_state
        state: '0.1'
    type: custom:sankey-chart
```

and drop the rest of that cared in a yaml anchor

**Describe alternatives you've considered**

an even better alternative would maybe be to add the entity_id if that input_select directly inside the config?

```
    type: custom:sankey-chart
    title: Energie onderverdeling
    min_state: input_select.sankey_min_state
```

**Additional context**

<img width="1215" alt="Image" src="https://github.com/user-attachments/assets/38e8ff53-f43f-4292-b666-39a4d0fbc0b4" />

**Comment by Mariusthvdb** [comment]
fwiw, ive been able to do it with `type: conditional` now and several yaml anchors:

```
type: vertical-stack
cards:
  - type: tile
    entity: input_select.sankey_min_state
    features:
      - type: select-options
    features_position: inline
  - type: conditional
    conditions:
      - condition: state
        entity: input_select.sankey_min_state
        state: '0'
    card:
      type: vertical-stack
      cards:
        - min_state: 0
          <<: &type_overzicht
            type: custom:sankey-chart
            title: Energie verbruik overzicht
          <<: &sankey_config
            show_names: true
            height: 500
            round: 2
            unit_prefix: k
            layout: horizontal
          <<: &sections_overzicht
            sections:

              - entities:
                  - entity_id: sensor.solar_energy_daily
                    name: Opbrengst Zon
                    color: gold
                    children:
                      - sensor.energy_consumed_daily
                      - sensor.calculated_totaal_dag_levering
///

        - min_state: 0
          <<: &type_onderverdeling
            type: custom:sankey-chart
            title: Energie onderverdeling
          <<: *sankey_config
          <<: &sections_onderverdeling
            sections:

              - entities:

                  - entity_id: sensor.energy_consumed_daily
                    name: Verbruik Huis
                    color: brown
                    children:
                      - sensor.gemeten_energie_per_dag
                      - sensor.ongemeten_energie_per_dag
///


  - type: conditional
    conditions:
      - condition: state
        entity: input_select.sankey_min_state
        state: '0.1'
    card:
      type: vertical-stack
      cards:
        - min_state: 0.1
          <<: *type_overzicht
          <<: *sankey_config
          <<: *sections_overzicht
        - min_state: 0.1
          <<: *type_onderverdeling
          <<: *sankey_config
          <<: *sections_onderverdeling

  - type: conditional
    conditions:
      - condition: state
        entity: input_select.sankey_min_state
        state: '0.2'
    card:
      type: vertical-stack
      cards:
        - min_state: 0.2
          <<: *type_overzicht
          <<: *sankey_config
          <<: *sections_overzicht
        - min_state: 0.2
          <<: *type_onderverdeling
          <<: *sankey_config
          <<: *sections_onderverdeling

  - type: conditional
    conditions:
      - condition: state
        entity: input_select.sankey_min_state
        state: '0.5'
    card:
      type: vertical-stack
      cards:
        - min_state: 0.5
          <<: *type_overzicht
          <<: *sankey_config
          <<: *sections_overzicht
        - min_state: 0.5
          <<: *type_onderverdeling
          <<: *sankey_config
          <<: *sections_onderverdeling

  - type: conditional
    conditions:
      - condition: state
        entity: input_select.sankey_min_state
        state: '1'
    card:
      type: vertical-stack
      cards:
        - min_state: 1
          <<: *type_overzicht
          <<: *sankey_config
          <<: *sections_overzicht
        - min_state: 1
          <<: *type_onderverdeling
          <<: *sankey_config
          <<: *sections_onderverdeling
```
