### ISSUE TITLE
InternalError: too much recursion & RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by scuppasteve** [MindFreeze/ha-sankey-chart#272]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:**
HA
Core - 2025.4.3
Supervisor - 2025.04.1
Operating System - 15.2
Frontend - 20250411.0

Sankey-Chart - v3.8.0

**Last working release (if known):**
N/A

**Browser and Operating System:**

**Firefox - InternalError: too much recursion**
Firefox 138.0 - Linux (docker) - Linuxserver.io version:- 138.0build1-0ubuntu0.24.04.1mt2-ls234 Build-date:- 2025-04-28T18:48:13+00:00
Firefox 138.0.1 - Windows 11 Pro 24H2
Firefox 138.0.1 - Mac Sequoia - 15.4.1

**Chrome - RangeError: Maximum call stack size exceeded**
Chrome 135.0.7049.116 - Windows 11 Pro 24H2
Chrome 135.0.7049.116 - Mac Sequoia - 15.4.1

**Edge - RangeError: Maximum call stack size exceeded**
Edge 136.0.3240.50 - Windows 11 Pro 24H2

**Description of problem:**

In Firefox it gives error of "InternalError: too much recursion" in Chrome/Edge it shows "RangeError: Maximum call stack size exceeded".

**Javascript errors shown in the web inspector (if applicable):**

```
InternalError: too much recursion
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
    _getEntityState https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js:1
[ha-sankey-chart.js:1:66809](https://172.20.251.10:8123/hacsfiles/ha-sankey-chart/ha-sankey-chart.js)
    render ha-sankey-chart.js:1
    update ha-sankey-chart.js:1
    performUpdate ha-sankey-chart.js:1
    scheduleUpdate ha-sankey-chart.js:1
    _$Ej ha-sankey-chart.js:1
    requestUpdate ha-sankey-chart.js:1
    set ha-sankey-chart.js:1
    j ha-sankey-chart.js:1
    _$AI ha-sankey-chart.js:1
    v ha-sankey-chart.js:1
    g ha-sankey-chart.js:1
    _$AI ha-sankey-chart.js:1
    Do ha-sankey-chart.js:1
    update ha-sankey-chart.js:1
    performUpdate ha-sankey-chart.js:1
    scheduleUpdate ha-sankey-chart.js:1
    _$Ej ha-sankey-chart.js:1
    requestUpdate ha-sankey-chart.js:1
    set ha-sankey-chart.js:1
    value hui-card.ts:190
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value hui-stack-card.ts:55
    value hui-stack-card.ts:54
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value hui-card.ts:190
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value hui-view.ts:261
    value hui-view.ts:260
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
```

**Additional information:**

My yaml
```
### Power Sankey ###
  - icon: mdi:chart-sankey-variant
    title: Sankey Dashboard
    type: panel
    cards:
      - type: vertical-stack
        cards:

          - type: custom:sankey-chart
            show_names: true
            round: 0
            min_state: 10
            layout: horizontal
            height: 800
            wide: true
            min_box_size: 10
            min_box_distance: 10
            sections:
              - entities:
                  - entity_id: sensor.solar_array_power_total
                    color: '#1e8449'
                    name: Sunpower Solar
                    children:
                      - sensor.total_power_use_w
                  - entity_id: sensor.envoy_202318115695_current_power_production
                    color: '#0aee2d'
                    name: Enphase Solar
                    children:
                      - sensor.total_power_use_w
                  - entity_id: sensor.grid_supplied_power_w
                    color: '#f00f0f'             
                    name: Grid
                    children:
                      - sensor.total_power_use_w
              - entities:
                  - entity_id: sensor.total_power_use_w
                    name: Total Power
                    color: '#0aeeea'
                    children:
                      - sensor.grid_returned_power_w
                      - sensor.total_other_power
                      - sensor.appliance_power
                      - sensor.garage_tools_power
                      - sensor.bedrooms_power
                      - sensor.total_ev_power_w
                      - sensor.it_power
                      - sensor.electronics_power
                      - sensor.hvac_power
                      - sensor.leisure_power
                      - sensor.common_spaces_power   
              - entities:
                  - entity_id: sensor.appliance_power
                    name: Appliances
                    color: '#02231c'
                    children:
                      - sensor.power_dryer
                      - sensor.power_washer
                      - sensor.power_dishwasher
                      - sensor.outlet_kitchen_garbage_disposal_power
                      - sensor.power_microwave
                      - sensor.power_fridge
                      - sensor.garage_freezer_power
                  - entity_id: sensor.bedrooms_power
                    name: Bedrooms
                    color: '#0c457d'
                    children:
                      - sensor.jaxon_s_bedroom_adjusted_power
                      - sensor.mason_s_bedroom_adjusted_power
                      - sensor.xander_s_bedroom_adjusted_power
                      - sensor.persephone_s_bedroom_adjusted_power
                      - sensor.spare_bedroom_adjusted_power
                      - sensor.master_bedroom_adjusted_power
                  - entity_id: sensor.common_spaces_power
                    name: Common Spaces
                    color: ''
                    children:
                      - sensor.computer_room_adjusted_power
                      - sensor.kitchen_adjusted_power
                      - sensor.living_room_adjusted_power
                  - entity_id: sensor.electronics_power
                    name: Electronics
                    children:
                      - sensor.outlet_living_room_entertainment_center_power
                      - sensor.outlet_living_room_subwoofer_power
                      - sensor.outlet_living_room_tv_power
                      - sensor.outlet_master_bedroom_av_power
                  - entity_id: sensor.total_ev_power_w
                    name: EV Chargers
                    children:
                      - sensor.tesla_east_ev_power_w
                      - sensor.tesla_west_ev_power_w
                  - entity_id: sensor.garage_tools_power
                    name: Garage
                    children:
                      - sensor.outlet_garage_3d_printer_power
                      - sensor.outlet_garage_air_compressor_power
                      - sensor.outlet_garage_air_filter_power
                      - sensor.power_bandsaw
                      - sensor.power_dust_collector
                      - sensor.power_festool_vacs
                      - sensor.power_planer
                      - sensor.garage_lighting_adjusted_power
                      - sensor.outlet_garage_overhead_tools_power
                      - sensor.outlet_garage_vacuum_power
                      - sensor.power_table_saw
                      - sensor.garage_workbench_adjusted_power
                  - entity_id: sensor.hvac_power
                    name: HVAC
                    children:
                      - sensor.power_air_conditioner
                      - sensor.power_furnace_fan
                      - sensor.power_whole_house_fan
                      - sensor.outlet_garage_fan_power
                  - entity_id: sensor.it_power
                    name: IT Stuff
                    color: '#f39c12'
                    children:
                      - sensor.rackups_w
                      - sensor.netups_w
                      - sensor.outlet_jaxon_s_bedroom_computer_power
                      - sensor.outlet_mason_s_bedroom_computer_power
                      - sensor.outlet_computer_room_xander_s_computer_power
                      - sensor.outlet_spare_bedroom_steve_s_office_power
                      - sensor.outlet_master_bedroom_gina_s_office_power
                  - entity_id: sensor.leisure_power
                    name: Leisure
                    color: '#ffc2cd'
                    children:
                      - sensor.power_hot_tub
                      - sensor.power_pool_sub_panel
              - sort_by: state
                entities:
# Appliances
                  - entity_id: sensor.power_dryer
                    color: '#36802d'
                    name: Dryer
                  - entity_id: sensor.power_washer
                    color: '#75fd71'
                    name: Washer                  
                  - entity_id: sensor.power_dishwasher
                    name: Dishwasher
                    color: '#77ab59'
                  - entity_id: sensor.outlet_kitchen_garbage_disposal_power
                    name: Garbage Disposal
                    color: '#77ab59'
                  - entity_id: sensor.power_microwave
                    name: Microwave
                    color: '#c9df8a'
                  - entity_id: sensor.power_fridge
                    name: Refrigerator
                    color: '#f0f7da'
                  - entity_id: sensor.garage_freezer_power
                    name: Garage Freezer
                    color: '#234d20'
# Appliances
# Bedrooms
                  - entity_id: sensor.jaxon_s_bedroom_adjusted_power
                    name: "Jaxon's Bedroom"
                    color: '#005073'
                  - entity_id: sensor.mason_s_bedroom_adjusted_power
                    name: "Mason's Bedroom"
                    color: '#1c3464'
                  - entity_id: sensor.xander_s_bedroom_adjusted_power
                    name: "Xander's Bedroom"
                    color: '#107dac'
                  - entity_id: sensor.persephone_s_bedroom_adjusted_power
                    name: "Persephone's Bedroom"
                    color: '#189ad3'
                  - entity_id: sensor.master_bedroom_adjusted_power
                    name: Master Bedroom
                    color: '#1ebbd7'
                  - entity_id: sensor.spare_bedroom_adjusted_power
                    name: Spare Bedroom
                    color: '#71c7ec'
# Bedrooms
# Common Spaces
                  - entity_id: sensor.computer_room_adjusted_power
                    color: '#f39c12'                    
                    name: Computer Room
                  - entity_id: sensor.kitchen_adjusted_power
                    color: '#ff6289'
                    name: Kitchen
                  - entity_id: sensor.living_room_adjusted_power
                    color: '#ff6289'
                    name: Living Room
# Common Spaces
# Electronics
                  - entity_id: sensor.outlet_living_room_entertainment_center_power
                    name: Living Room - AV
                  - entity_id: sensor.outlet_living_room_tv_power
                    name: Living Room - TV
                  - entity_id: sensor.outlet_living_room_subwoofer_power
                    name: Living Room - Subwoofer
                  - entity_id: sensor.outlet_master_bedroom_av_power
                    name: Master Bedroom - AV
# Electronics
# EV Chargers
                  - entity_id: sensor.tesla_east_ev_power_w
                    name: East EV Charger
                  - entity_id: sensor.tesla_west_ev_power_w
                    name: West EV Charger
# EV Chargers
# Garage Tools
                  - entity_id: sensor.outlet_garage_3d_printer_power
                    name: "3D Printer"
                  - entity_id: sensor.outlet_garage_air_compressor_power
                    name: Air Compressor
                  - entity_id: sensor.outlet_garage_air_filter_power
                    name: Air Filter
                  - entity_id: sensor.power_bandsaw
                    name: Bandsaw
                  - entity_id: sensor.power_dust_collector
                    name: Dust Collector
                  - entity_id: sensor.power_festool_vacs
                    name: "Festool Vacs"
                  - entity_id: sensor.power_planer
                    name: "Jointer/Planer"
                  - entity_id: sensor.garage_lighting_adjusted_power
                    name: Garage Lights
                  - entity_id: sensor.outlet_garage_overhead_tools_power
                    name: Overhead Tools
                  - entity_id: sensor.outlet_garage_vacuum_power
                    name: Shopvac
                  - entity_id: sensor.power_table_saw
                    name: Table Saw
                  - entity_id: sensor.garage_workbench_adjusted_power
                    name: Workbench
# Garage Tools
# HVAC
                  - entity_id: sensor.power_air_conditioner
                    name: A/C
                  - entity_id: sensor.power_furnace_fan
                    name: Furnace Fan
                  - entity_id: sensor.power_whole_house_fan
                    name: Whole House Fan
                  - entity_id: sensor.outlet_garage_fan_power
                    name: Garage Fan
# HVAC
# IT
                  - entity_id: sensor.rackups_w
                    color: '#ee530a'
                    name: Rack UPS
                  - entity_id: sensor.netups_w
                    color: '#f4d03f'
                    name: Net UPS
                  - entity_id: sensor.outlet_jaxon_s_bedroom_computer_power
                    name: "Jaxon's Computer"
                  - entity_id: sensor.outlet_mason_s_bedroom_computer_power
                    name: "Mason's Computer"
                  - entity_id: sensor.outlet_computer_room_xander_s_computer_power
                    name: "Xander's Computer"
                  - entity_id: sensor.outlet_spare_bedroom_steve_s_office_power
                    name: "Steve's Office"
                  - entity_id: sensor.outlet_master_bedroom_gina_s_office_power
                    name: "Gina's Office"
# IT
# Leisure
                  - entity_id: sensor.power_hot_tub
                    color: '#ff6289'
                    name: Hot Tub
                  - entity_id: sensor.power_pool_sub_panel
                    color: '#ff084a'
                    name: Pool
# Leisure
# Power Returned to Grid
                  - entity_id: sensor.grid_returned_power_w
                    color: '#f00f0f'
                    name: Grid
                    type: passthrough
# Power Returned to Grid
# Total Other Power
                  - entity_id: sensor.total_other_power
                    color: '#ff084a'
                    name: Other
                    type: passthrough
# Total Other Power
### Power Sankey ###
```
