### ISSUE TITLE
I need help visualizing energy shares of various consumers.

### ISSUE THREAD

**Issue by thoath2** [MindFreeze/ha-sankey-chart#275]
Hello,
I was able to successfully configure a ha-sankey chart, where I represent
- Three different energy sources as the starting point (PV-Erzeugung, Batt.-Entladung, Netzbezug)
- Intercounters and exits
- Different consumers

You can see this in the picture.

<img width="710" alt="Image" src="https://github.com/user-attachments/assets/6d2d5213-126f-4718-a85b-3c5993615c3f" />

My big goal is now to add another child level that includes exactly 3 child elements for each consumer, which divides the consumption amount according to the sources of receipt.
For example:
Heat pump 1366.5 kWh 
- Child 1: PV share: 739.2kWh 
- Child 2: Batt. Discharge share: 107.33 kWh 
-Child 3: Network cover share: 519.9 kWh

How can I do this. Do you have an idea?
I had already tried to add another level and work with "Passtrough". But there was a mistake "too many recursions.

regards Thomas

Here is the yaml-Code:
```
type: custom:sankey-chart
grid_options:
  columns: full
min_state: 0
title: PV-Verteilung
wide: true
layout: auto
height: 200
unit_prefix: k
round: 1
convert_units_to: ""
min_box_size: 5
min_box_distance: 5
show_states: true
show_units: true
show_names: true
show_icons: true
energy_date_selection: true
sections:
  - entities:
      - entity_id: sensor.pv_stromzaehler_gesamt_wirkenergie_mit_offset
        type: entity
        name: PV-Erzeugung
        color: var(--energy-solar-color)
        children:
          - gesamt_verbrauch
      - entity_id: sensor.pv_batterie_entladung_energie_offset
        type: entity
        name: Batt.-Entladung
        color: var(--success-color)
        children:
          - gesamt_verbrauch
      - entity_id: sensor.z1_stromzaehler_energie_bezug_mit_offset
        type: entity
        name: Netzbezug
        color: var(--energy-grid-consumption-color)
        children:
          - gesamt_verbrauch
  - entities:
      - entity_id: gesamt_verbrauch
        type: remaining_parent_state
        name: Gesamtverbrauch
        children:
          - entity_id: sensor.pv_batterie_ladung_energie_offset
          - entity_id: sensor.z1_stromzaehler_energie_einspeisung_mit_offset
          - netto_verbrauch
  - entities:
      - entity_id: sensor.pv_batterie_ladung_energie_offset
        type: entity
        name: Batt.Ladung
        children: []
        color: var(--success-color)
      - entity_id: sensor.z1_stromzaehler_energie_einspeisung_mit_offset
        type: entity
        name: Netzeinspeisung
        children: []
        color: var(--energy-solar-color)
      - type: remaining_parent_state
        children:
          - sensor.wp_separat_elektrische_energie_mit_offset
          - peripherie
          - sensor.eg_stromzaehler_gesamt_wirkenergie_mit_offset
          - sensor.dg_stromzaehler_gesamt_wirkenergie_mit_offset
          - sensor.gem_stromzaehler_gesamt_wirkenergie_mit_offset
        entity_id: netto_verbrauch
        name: Nettoverbrauch
        color: purple
  - entities:
      - entity_id: sensor.wp_separat_elektrische_energie_mit_offset
        type: entity
        name: Wärmepumpe
        children: []
      - entity_id: peripherie
        type: remaining_parent_state
        name: Heizperipherie
        children: []
      - entity_id: sensor.eg_stromzaehler_gesamt_wirkenergie_mit_offset
        type: entity
        name: Erdgeschoss
        children: []
      - entity_id: sensor.dg_stromzaehler_gesamt_wirkenergie_mit_offset
        type: entity
        name: Dachgeschoss
        children: []
      - entity_id: sensor.gem_stromzaehler_gesamt_wirkenergie_mit_offset
        type: entity
        name: Gemeinschaft
        children: []

```
