### ISSUE TITLE
Cannot use a 5th section

### ISSUE THREAD

**Issue by sybux** [MindFreeze/ha-sankey-chart#288]
**Description of problem:**

I'm creating a energy consumption for my DataCenter. I will have :
Level 1 :
  - source A
  - Source B
Level 2 :
  - centralised power
Level 3 :
  - PDU consumption
  - Climate consumption
Level 4 :
  - distribution rail 1
  - distribution rail 2
  - distribution rail 3
  - distribution rail 4
  - distribution rail 5
  - distribution rail 6
  - Air-conditioner
  - cold water production
Level 5 :
  - 2 to 4 PDU for each rail
  - Conditioner 1
  - conditioner 2
  - conditioner 3
  - cold water 1
  - cold water 2

I can get level 1 to level 4 with no problem, but I cannot find a way to display level 5.
All values are from device or helpers.
Even worth, as you can see on picture, Clim 1, 2 and 3 are linked to PDU in stead of Clim B412 (which is not the case in the yaml file

![Image](https://github.com/user-attachments/assets/8088d60f-66fd-41e1-9051-b0ff53f4a3a4)

**Comment by MindFreeze** [comment]
Please post your yaml config. Otherwise I can't guess what the issue might be

**Comment by sybux** [comment]
here it is : 
```
layout: horizontal
height: 400
unit_prefix: k
round: 1
convert_units_to: ""
co2_intensity_entity: sensor.co2_signal_co2_intensity
gas_co2_intensity: 2351.6459999999997
min_box_size: 4
min_box_distance: 5
show_states: true
show_units: true
sections:
  - entities:
      - children:
          - sensor.distribution_prairie_sts_energy
        entity_id: sensor.ups_p_a_kwh
        color: yellow
  - entities:
      - children:
          - sensor.pdu_p_total_kwh
          - sensor.clim_p_total_kwh
        entity_id: sensor.distribution_prairie_sts_energy
        color: yellow
        name: STS - Distribution B412
        icon: mdi:transmission-tower
  - entities:
      - children:
          - sensor.p_iot_b412_31q1_total_active_energy
          - sensor.p_iot_b412_31q4_total_active_energy
          - sensor.p_iot_b412_31q7_total_active_energy
          - sensor.p_iot_b412_32q1_total_active_energy
          - sensor.p_iot_b412_32q4_total_active_energy
          - sensor.p_iot_b412_32q7_total_active_energy
        entity_id: sensor.pdu_p_total_kwh
        color: red
        name: Total PDU
        icon: mdi:lightning-bolt-outline
      - children:
          - sensor.p_iot_b412_33q1_total_active_energy
          - sensor.p_iot_b412_33q4_total_active_energy
          - sensor.p_iot_b412_33q7_total_active_energy
        entity_id: sensor.clim_p_total_kwh
        color: blue
        name: Clim B412
        icon: mdi:air-conditioner
  - entities:
      - children:
          - sensor.pdu_p_af05r1_a_kwh
          - sensor.pdu_p_af05r2_a_kwh
          - sensor.pdu_p_af05r3_a_kwh
        entity_id: sensor.p_iot_b412_31q1_total_active_energy
        color: red
        name: Rail 1
        icon: mdi:transmission-tower
      - children:
          - sensor.pdu_p_af05r1_b_kwh
          - sensor.pdu_p_af05r2_b_kwh
          - sensor.pdu_p_af05r3_b_kwh
        entity_id: sensor.p_iot_b412_31q4_total_active_energy
        color: red
        name: Rail 2
        icon: mdi:transmission-tower
      - children:
          - sensor.pdu_p_af03r1_a_kwh
          - sensor.pdu_p_af03r2_a_kwh
          - sensor.pdu_p_af03r3_a_kwh
          - sensor.pdu_p_af03r4_a_kwh
        entity_id: sensor.p_iot_b412_31q7_total_active_energy
        color: red
        name: Rail 3
        icon: mdi:transmission-tower
      - children:
          - sensor.pdu_p_af03r1_b_kwh
          - sensor.pdu_p_af03r2_b_kwh
          - sensor.pdu_p_af03r3_b_kwh
          - sensor.pdu_p_af03r4_b_kwh
        entity_id: sensor.p_iot_b412_32q1_total_active_energy
        color: red
        name: Rail 4
        icon: mdi:transmission-tower
      - children:
          - sensor.pdu_p_af01r2_a_kwh
        entity_id: sensor.p_iot_b412_32q4_total_active_energy
        color: red
        name: Rail 5
        icon: mdi:transmission-tower
      - children:
          - sensor.pdu_p_af01r2_b_kwh
        entity_id: sensor.p_iot_b412_32q7_total_active_energy
        color: red
        name: Rail 6
        icon: mdi:transmission-tower
      - children: []
        entity_id: sensor.p_iot_b412_33q1_total_active_energy
        color: cyan
        name: Clim 1
        icon: mdi:air-conditioner
      - children: []
        entity_id: sensor.p_iot_b412_33q4_total_active_energy
        color: cyan
        name: Clim 2
        icon: mdi:air-conditioner
      - children: []
        entity_id: sensor.p_iot_b412_33q7_total_active_energy
        color: cyan
        name: Clim 2
        icon: mdi:air-conditioner
  - entities:
      - children: []
        entity_id: sensor.pdu_p_af05r1_a_kwh
        color: purple
        name: AF05R1 - A
      - children: []
        entity_id: sensor.pdu_p_af05r2_a_kwh
        color: purple
        name: AF05R2 - A
      - children: []
        entity_id: sensor.pdu_p_af05r3_a_kwh
        color: purple
        name: AF05R3 - A
      - children: []
        entity_id: sensor.pdu_p_af05r1_b_kwh
        color: purple
        name: AF05R1 - B
      - children: []
        entity_id: sensor.pdu_p_af05r2_b_kwh
        color: purple
        name: AF05R2 - B
      - children: []
        entity_id: sensor.pdu_p_af05r3_b_kwh
        color: purple
        name: AF05R3 - B
      - children: []
        entity_id: sensor.pdu_p_af03r1_a_kwh
        name: AF03R1 - A
        color: purple
      - children: []
        entity_id: sensor.pdu_p_af03r1_b_kwh
        color: purple
        name: AF03R1 - B
      - children: []
        entity_id: sensor.pdu_p_af03r2_a_kwh
        color: purple
        name: AF03R2 - A
      - children: []
        entity_id: sensor.pdu_p_af03r2_b_kwh
        color: purple
        name: AF03R2 - B
      - children: []
        entity_id: sensor.pdu_p_af03r3_a_kwh
        color: purple
        name: AF03R3 - A
      - children: []
        entity_id: sensor.pdu_p_af03r3_b_kwh
        color: purple
        name: AF03R3 - B
      - children: []
        entity_id: sensor.pdu_p_af03r4_a_kwh
        color: purple
        name: AF03R4 - A
      - children: []
        entity_id: sensor.pdu_p_af03r4_b_kwh
        color: purple
        name: AF03R4 - B
      - children: []
        entity_id: sensor.pdu_p_af01r2_a_kwh
        color: purple
        name: AF01R2 - A
      - children: []
        entity_id: sensor.pdu_p_af01r2_b_kwh
        color: purple
        name: AF01R2 - B
energy_date_selection: true
type: custom:sankey-chart
min_state: 0
wide: true
show_icons: true
show_names: true
grid_options:
  columns: 48
  rows: 8

```
