### ISSUE TITLE
Allow for 'Virtual' Entities

### ISSUE THREAD

**Issue by Madelena** [MindFreeze/ha-sankey-chart#3]
Creating a detailed Sankey Chart requires making template sensors with the sum of the values of its children. It would be nice to not having such requirement, as I end up having to create a ton of templates that are only used for this chart but nowhere else.

**Describe the solution you'd like**
It will be nice to have the ability to point to a node without an entity_id:

```
sections:
  - entities:
    - entity_id: sensor.house_total
      children:
        - node.floor1
        - node.floor2
        - node.outdoors
  - entities:
    - node: floor1
      children:
        - sensor.airconditioner
        - sensor.stove
    - node: floor2
      children:
        - sensor.computer
        - sensor.bedlight
    - node: outdoors
      children:
        - sensor.floodlights
  - entities:
    - sensor.airconditioner
    - sensor.stove
    - sensor.computer
    - sensor.bedlight
    - sensor.floodlights
```

**Describe alternatives you've considered**
I created a dozen template entities that are sum of the values of various sensors.
