### ISSUE TITLE
Remaining object does not show when one of the entities has a value of 0

### ISSUE THREAD

**Issue by iridris** [MindFreeze/ha-sankey-chart#30]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
core-2022.8.0
**Last working release (if known):**
n/a
**Browser and Operating System:**
Firefox & Chrome on Windows 10, HA mobile app

**Description of problem:**
The remaining object does not show when one of the child entities has a value of 0. In the following example, the entity `sensor.washing_machine_power_meter_meter` has a value of 0w. The remaining object does not show. If that particular entity is either commented out, or made to have a value above 0, the remaining object will appear.

```
type: custom:sankey-chart
title: Power
show_names: true
min_box_height: 20
sections:
  - entities:
      - entity_id: sensor.breaker_panel_power_meter
        name: Total
        remaining:
          name: All Others
        children:
          - sensor.pool_pump_power_meter
          - sensor.office_big_light_power_meter
          - sensor.washing_machine_power_meter_meter
  - entities:
      - entity_id: sensor.washing_machine_power_meter
        name: Washer
      - entity_id: sensor.pool_pump_power_meter
        name: Network Rack
        children:
          - sensor.idrac_host1_powerconsumption
          - sensor.idrac_host2_powerconsumption
          - sensor.idrac_host3_powerconsumption
        remaining:
          name: Other Network
      - entity_id: sensor.office_big_light_power_meter
        name: Driveway Cam
  - entities:
      - entity_id: sensor.idrac_host1_powerconsumption
        name: Host 1
      - entity_id: sensor.idrac_host2_powerconsumption
        name: Host 2
      - entity_id: sensor.idrac_host3_powerconsumption
        name: Host 3
```
Screenshot of the Sankey chart with child `sensor.washing_machine_power_meter_meter` having a value of 0, note the 'All Others' remaining object is missing:
![image](https://user-images.githubusercontent.com/952387/182690837-753f06d3-c31f-4259-9bfd-ef5a53b94899.png)
Screenshot of the Saneky chart with child `sensor.washing_machine_power_meter_meter` removed/commented out, note the 'All Others' remaining object is present:
![image](https://user-images.githubusercontent.com/952387/182690953-a212cc49-9036-446e-b98f-4a86dd0f576a.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
