### ISSUE TITLE
allow custom icons in sankey-chart

### ISSUE THREAD

**Issue by f-zappa** [MindFreeze/ha-sankey-chart#68]
The sankey-chart can show icons (option "show_icons: yes"), but it uses the default ones from the entity. I'd like to use different icons with the chart, configuration could look like the following:
```
sections:
  - entities:
      - entity_id: sensor.total_dc_power
        name: PV
        icon: mdi:solar-power      <----
        color: yellow
        children:
          - sensor.load
```
Would it please be possible to integrate this?
Regards, Uli

**Comment by mb-software** [comment]
I agree that would be very helpful

**Comment by mb-software** [comment]
Something to add on this: Is it possible to increase the width of the bar where the icons sit? Currently many icons are too wide and it does not look very nice.
![image](https://user-images.githubusercontent.com/36257766/211548285-7adf86fd-4d75-4261-a7fe-13e28c379647.png)

**Comment by MindFreeze** [comment]
@mb-software you can do stuff like that with card-mod. I can't add an option for every css property or the card will become too slow

**Comment by mb-software** [comment]
> @mb-software you can do stuff like that with card-mod. I can't add an option for every css property or the card will become too slow

Sure. But in my opinion this should not be an option, it should just be adjusted by default. Currently the option show_icons makes not much sense, because most icons are not shown properly.
Anyway, I already tried it with card-mod, but couldn't get the width adjusted. Can you guide me to the correct styles entry with card-mod?

**Comment by MindFreeze** [comment]
The css for width is
```css
.box div:first-child {
        width: 15px;
}
.connectors {
    left: 15px;
}
```
You have to adjust both or the branches will be detached. Which is actually a desired effect for some ppl
