### ISSUE TITLE
Autoconfig setup 

### ISSUE THREAD

**Issue by Dutchy-79** [MindFreeze/ha-sankey-chart#76]
Hi, 

Not a bug though I tried setting up the autoconfig and it does not work. 

Must be my fault but I don't see any other way in the Readme then copy paste this

```
-type: energy-date-selection # you can put this anywhere you want but it is required for energy dashboard integration 
- type: custom:sankey-chart
  # ...any other options
  autoconfig:
    print_yaml: false # optional
    # any additional autoconfig options (listed below)
```
Into a empty card on my dashboard. 

![Screenshot_20230118_135334_Home Assistant](https://user-images.githubusercontent.com/22749572/213176705-eec55987-052d-4f18-9855-494f5f91b21f.png)

Maybe someone could help me out what I'm doing wrong?
