### ISSUE TITLE
Notes and passthrough on chosen places 

### ISSUE THREAD

**Issue by Dutchy-79** [MindFreeze/ha-sankey-chart#85]
Hi,

I'm really starting to get the design though I have a few questions.

I made notes on the yaml using

# kitchen
Entity_id: etc.

But they are deleted on saving the file.

And I have a passthrough that doesn't go where I want to.

![Screenshot_20230122_122924_Home Assistant](https://user-images.githubusercontent.com/22749572/213914357-d1d38375-a928-4832-b051-6707f2ecaa14.png)

I want to see it going on the top instead dropping down.

My code

```
type: custom:sankey-chart
height: 400
witdh: 800
unit_prefix: k
round: 1
min_box_height: 3
min_box_distance: 5
show_states: true
show_units: true
show_names: true
energy_date_selection: true
sections:
  - entities:
      - entity_id: sensor.solaredge_platte_dak_lifetime_energy
        type: entity
        color: var(--warning-color)
        children:
          - zon
      - entity_id: sensor.solaredge_schuur_lifetime_energy
        type: entity
        color: var(--warning-color)
        children:
          - zon
      - entity_id: sensor.energieverbruik_hoog
        type: entity
        color: gray
        children:
          - totalbuy
      - entity_id: sensor.energieverbruik_laag
        type: entity
        color: gray
        children:
          - totalbuy
  - entities:
      - entity_id: zon
        type: remaining_parent_state
        name: Totaal Zon
        color: var(--warning-color)
        children:
          - teruglevering
          - total
      - entity_id: totalbuy
        type: remaining_parent_state
        name: Totaal Inkoop
        color: gray
        children:
          - total
  - entities:
      - entity_id: teruglevering
        type: remaining_child_state
        color: var(--warning-color)
        name: Teruglevering
        children:
          - sensor.energie_teruglevering_hoog
          - sensor.energie_teruglevering_laag
      - entity_id: total
        substract_entities:
          - sensor.energie_teruglevering_hoog
          - sensor.energie_teruglevering_laag
        type: remaining_parent_state
        name: Total Consumption
        color: lightgreen
        children:
          - keuken
          - slaapkamer
          - waskamer
          - woonkamer
          - badkamer
          - slaapkamer_jenniffer
          - wc
          - overige
  - entities:
      - entity_id: sensor.teruglevering
        type: passthrough
        children:
          - sensor.teruglevering
      - entity_id: keuken
        type: remaining_child_state
        name: Keuken
        color: turquoise
        children:
          - sensor.boiler_energy_total
          - sensor.airco_keuken_verbruik_helper
          - sensor.speaker_keuken_energy
      - entity_id: slaapkamer
        type: remaining_child_state
        name: Slaapkamer
        color: pink
        children:
          - sensor.stekker_waterbed_energy_total
          - sensor.lichtschakelaar_slaapkamer_energy
      - entity_id: waskamer
        type: remaining_child_state
        name: Waskamer
        color: yellow
        children:
          - sensor.wasmachine_energy
          - sensor.wasmachine_kwh_meter
          - sensor.ir_paneel_kwh_meter
      - entity_id: woonkamer
        type: remaining_child_state
        name: Woonkamer
        color: purple
        children:
          - sensor.airco_huiskamer_kwh
          - sensor.verbruik_tv
          - sensor.lamp_op_tv_kast_energy
          - sensor.lamp_op_vitrine_kast_energy
          - sensor.googlehome4153_energy
      - entity_id: slaapkamer_jenniffer
        type: remaining_child_state
        name: Slaapkamer Jenniffer
        color: violet
        children:
          - sensor.airco_jen_kwh_sensor_helper
      - entity_id: badkamer
        type: remaining_child_state
        name: Badkamer
        color: red
        children:
          - sensor.badkamer_ventilator_verbruik_energy
          - sensor.badkamer_verlichting_verbruik_energy
          - sensor.warmtepompboiler_verbruik
      - entity_id: wc
        type: remaining_child_state
        name: WC
        color: blue
        children:
          - sensor.licht_wc_energy
      - entity_id: overige
        type: remaining_parent_state
        name: Overige
        color: green
        children: []
  - entities:
      - entity_id: sensor.energie_teruglevering_hoog
        type: entity
        color: var(--warning-color)
        children: []
      - entity_id: sensor.energie_teruglevering_laag
        type: entity
        color: var(--warning-color)
        children: []
      - entity_id: sensor.airco_keuken_verbruik_helper
        type: entity
        color: turquoise
        children: []
      - entity_id: sensor.boiler_energy_total
        type: entity
        color: turquoise
        children: []
      - entity_id: sensor.speaker_keuken_energy
        type: entity
        color: turquoise
        children: []
      - entity_id: sensor.stekker_waterbed_energy_total
        type: entity
        color: pink
        children: []
      - entity_id: sensor.lichtschakelaar_slaapkamer_energy
        type: entity
        color: pink
        children: []
      - entity_id: sensor.wasmachine_energy
        type: entity
        color: yellow
        children: []
      - entity_id: sensor.wasmachine_kwh_meter
        type: entity
        color: yellow
        children: []
      - entity_id: sensor.ir_paneel_kwh_meter
        type: entity
        color: yellow
        children: []
      - entity_id: sensor.airco_huiskamer_kwh
        type: entity
        color: purple
        children: []
      - entity_id: sensor.verbruik_tv
        type: entity
        color: purple
        children: []
      - entity_id: sensor.lamp_op_tv_kast_energy
        type: entity
        color: purple
        children: []
      - entity_id: sensor.lamp_op_vitrine_kast_energy
        type: entity
        color: purple
        children: []
      - entity_id: sensor.googlehome4153_energy
        type: entity
        color: purple
        children: []
      - entity_id: sensor.airco_jen_kwh_sensor_helper
        type: entity
        color: violet
        children: []
      - entity_id: sensor.badkamer_ventilator_verbruik_energy
        type: entity
        color: red
        children: []
      - entity_id: sensor.badkamer_verlichting_verbruik_energy
        type: entity
        color: red
        children: []
      - entity_id: sensor.warmtepompboiler_verbruik
        type: entity
        color: red
        children: []
      - entity_id: sensor.licht_wc_energy
        type: entity
        color: blue
        children: []
```
