### ISSUE TITLE
Max-width of Sankey Chart

### ISSUE THREAD

**Issue by Xitro01** [MindFreeze/ha-sankey-chart#86]
The chart seems to ignore the max-width or isn't changing its size accordingly.
When I remove the card all other cards remain within the borders, but whenever I place the sankey chart all the cards are going out of bounds.

![Schermafbeelding 2023-01-23 102954](https://user-images.githubusercontent.com/19844787/214006460-03353426-5022-45ef-ab95-fe0ab3452cab.png)

I'm not really a CSS hero, so I have no clue what might be causing this.

**Comment by MindFreeze** [comment]
I can't reproduce this. My cards scale fine with and without the `wide` option. What is your config like? Do you have it in a vertical-stack or similar card?

**Comment by Xitro01** [comment]
> I can't reproduce this. My cards scale fine with and without the `wide` option. What is your config like? Do you have it in a vertical-stack or similar card?

This is the whole config:
```
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Energie
    size: wide
    content:
      type: custom:layout-card
      layout_type: grid
      layout:
        grid-template-columns: 33% 33% 33%
        grid-template-rows: auto
        grid-template-areas: |
          "main main2 main3"
        grid-gap: 5px
        mediaquery:
          #phone
          "(max-width: 800px)":
            grid-template-columns: 2fr
            grid-template-rows: repeat(2, 2fr)
            grid-template-areas: |
              "main"
              "main2"
              "main3"
            grid-gap: 5px
      cards:
        - type: vertical-stack
          cards:
            - type: energy-date-selection
            - type: energy-usage-graph
          view_layout:
          grid-area: main
        - type: vertical-stack
          cards:
            - type: energy-solar-graph
            - type: energy-gas-graph
          view_layout:
          grid-area: main2
        - type: vertical-stack
          cards:
            - type: energy-distribution
            - type: energy-devices-graph
            - type: custom:sankey-chart
              autoconfig:
                print_yaml: false
              show_names: true
          view_layout:
          grid-area: main3
```
