### ISSUE TITLE
Autoconfig throws error

### ISSUE THREAD

**Issue by michalk-k** [MindFreeze/ha-sankey-chart#89]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.9.3
**Last working release (if known):**
N/A
**Browser and Operating System:**
Chrome @ Fedora
**Description of problem:**

When attempting to use autoconfig the card throws error:

![image](https://user-images.githubusercontent.com/7868445/214297864-e40e543d-f25a-4f19-8a30-8784cba1cbc3.png)

The pcroom likely refers to area. I'm not using areas in any serious way, assigning them to entities from time to time.

Here is a dashboard code:
```
title: Energy3
views:
  - path: default_view
    title: Energy3
    cards:
      - type: energy-date-selection
      - type: custom:sankey-chart
        autoconfig:
          print_yaml: false
```

and the data from HA API:
`JSON.stringify((await hassConnection).conn._energy.prefs.energy_sources)`
```json
[{"type":"grid","flow_from":[{"stat_energy_from":"sensor.total_electric_consumption","stat_cost":null,"entity_energy_from":"sensor.total_electric_consumption","entity_energy_price":null,"number_energy_price":null},{"stat_energy_from":"sensor.cube_electric_consumption","stat_cost":null,"entity_energy_from":"sensor.cube_electric_consumption","entity_energy_price":null,"number_energy_price":null}],"flow_to":[],"cost_adjustment_day":0}]
```
**Javascript errors shown in the web inspector (if applicable):**

![image](https://user-images.githubusercontent.com/7868445/214298981-2c142eb3-ac0c-418f-967e-822a9a4141cd.png)

**Additional information:**
