### ISSUE TITLE
Runtime error RangeError: toFixed() 

### ISSUE THREAD

**Issue by mattsaxon** [MindFreeze/ha-sankey-chart#90]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
2023.1.7 of HA, 1.9.3 of ha-sankey-chart
**Last working release (if known):**
None
**Browser and Operating System:**
Chrome 109.0.5414.120 (Official Build) (64-bit) on Windows 11 

**Description of problem:**

For a working configuration (most of the time) I sometime get an runtime error displayed in the UI

```
RangeError: toFixed() argument must be between 0 and 100
```

**Additional information:**
I suspect this is when one of the calculated measurement (total) would be below negative, but cannot be sure at the moment

I will post additional information as I have it, but there is only a single call to toFixed() in the code and the surrounding code has no range checking. I will try to add some to see if this resolves the issue,

````
type: custom:sankey-chart
show_names: true
show_icons: false
wide: false
title: Spot Power Usage
sections:
  - entities:
      - entity_id: sensor.net_solar_power
        color: var(--warning-color)
        name: Solar
        children:
          - sensor.immersion_power
          - total
      - entity_id: sensor.house_channel_1_power
        name: Grid
        children:
          - sensor.immersion_power
          - total
  - entities:
      - entity_id: sensor.immersion_power
        color: var(--success-color)
      - entity_id: total
        type: remaining_parent_state
        substract_entities:
          - sensor.grid_return_power
          - sensor.immersion_power
        name: Total
        children:
          - sensor.net_barn_power
          - other_house
          - sensor.appliances
          - sensor.media
          - sensor.lexis_desk_active_power
          - sensor.tz3000_typdpbpg_ts011f_active_power
      - entity_id: sensor.grid_return_power
        color: var(--error-color)
  - entities:
      - entity_id: sensor.net_barn_power
        name: Barn
        children:
          - sensor.matts_desk_active_power
          - other_barn
      - entity_id: other_house
        type: remaining_parent_state
        name: Other House
      - entity_id: sensor.appliances
        children:
          - sensor.dishwasher_electricalmeasurement_2
          - sensor.washing_machine_electricalmeasurement_2
          - sensor.tumbledrier_electricalmeasurement
          - sensor.freezer_active_power
          - sensor.fridge_active_power
      - entity_id: sensor.media
        children:
          - sensor.marantz_master_power_electricalmeasurement_2
          - sensor.tz3000_typdpbpg_ts011f_electricalmeasurement
          - sensor.media_server_active_power_2
          - sensor.speakercraft_2_active_power_2
  - entities:
      - sensor.matts_desk_active_power
      - entity_id: other_barn
        type: remaining_parent_state
        name: Other Barn
      - entity_id: other_house
        type: remaining_parent_state
        name: Other House
      - sensor.dishwasher_electricalmeasurement_2
      - sensor.washing_machine_electricalmeasurement_2
      - sensor.tumbledrier_electricalmeasurement
      - sensor.freezer_active_power
      - sensor.fridge_active_power
      - sensor.marantz_master_power_electricalmeasurement_2
      - sensor.tz3000_typdpbpg_ts011f_electricalmeasurement
      - sensor.media_server_active_power_2
      - sensor.speakercraft_2_active_power_2
      - sensor.lexis_desk_active_power
      - sensor.tz3000_typdpbpg_ts011f_active_power
````
