### ISSUE TITLE
Parent/Child colors reversed

### ISSUE THREAD

**Issue by GitHubGoody** [MindFreeze/ha-sankey-chart#96]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** v1.9.3

**Last working release (if known):** N/A

**Browser and Operating System:** Edge on Windows 10

**Description of problem:**

Sometimes, the colors between parent and child display reversed as shown in the screenshot below between Grid and Outside.

**Javascript errors shown in the web inspector (if applicable):** None

**Additional information:**

![image](https://user-images.githubusercontent.com/46235745/220095687-f12d9734-2c2a-43aa-b4b7-a9997a9522c9.png)

**Comment by MindFreeze** [comment]
I can't reproduce this or figure out how it might happen

**Comment by MindFreeze** [comment]
closing as unreproducable

**Comment by GitHubGoody** [comment]
@MindFreeze Is there something I could do to help you reproduce it?

**Comment by MindFreeze** [comment]
@GitHubGoody an example config to reproduce this might help

**Comment by starox** [comment]
I just have some strange behaviour where the 4th section color was inversed with the 1st.
It was caused by an improper color name, ie: light_blue instead LightBlue
@GitHubGoody : Eventually check your colors

**Comment by GitHubGoody** [comment]
@MindFreeze and @starox

Here is the config excerpt for those two sections:

            - entities:
                  # Main Panel
                - entity_id: sensor.main_panel_123_1d
                  name: Grid
                  color_on_state: true
                  color_limit: 90
                  color_above: red
                  color_below: darkslateblue
                  children:
                    - sensor.inside_daily_energy
                    - sensor.outside_daily_energy
                    - sensor.garage_daily_energy
                    - sensor.receptacles_energy
                    - sensor.main_crawlspace_dehumidifier_7_1d
                    - sensor.sunroom_crawlspace_dehumidifier_and_sump_pump_8_1d
            - entities:
                  ## Outside
                - entity_id: sensor.outside_daily_energy
                  name: Outside
                  color: green
                  children:
                    - sensor.terrace_energy
                    - sensor.outside_lights_energy
                    - sensor.pool_energy
                  ## Inside
                - entity_id: sensor.inside_daily_energy
                  name: Inside
                  color: whitesmoke
                  children:
                    - sensor.upstairs_daily_energy
                    - sensor.downstairs_daily_energy
                    - sensor.ac_subpanel_1_1d

The colors all seem to be working otherwise.

**Comment by silfax** [comment]
Ok, having a similar problem. I say it is similar since the colors can be reversed but also totally wrong. First I encountered the reversed colors issue, but after doing lots of changes in the code, I ended up with the result in the second screenshot. I really don't know what info would be relevant, therefore I leave below all my 'sections' section of the card. Please note that this always occurs only at the top, not with the specific entities shown in the screenshot. Being an energy card, any of the groups can move at the top and the colors are always reverted for the topmost group. Screenshots and code below.

Screenshot 1, colors reversed, sadly I don't have the code anymore:
<img src="https://github.com/MindFreeze/ha-sankey-chart/assets/65038681/4c500a43-a68c-48ae-829c-c13ddfbe1213.png" width=50% height=50%>

Screenshot 2, wrong/messed up colors, code for this issue below:
![image](https://github.com/MindFreeze/ha-sankey-chart/assets/65038681/7dec7387-afdd-40be-a281-f25e6d7f3237)
```
sections:
  - entities:
      - type: entity
        entity_id: sensor.inverter_active_power
        children:
          - sensor.putere_instantanee
          - sensor.power_meter_active_power
        color: green
        name: Productie
      - type: entity
        entity_id: sensor.putere_instantanee
        children:
          - sensor.putere_instantanee
        subtract_entities:
          - sensor.inverter_active_power
        color: red
        name: Import
  - entities:
      - type: entity
        entity_id: sensor.power_meter_active_power
        color: red
        name: Export
      - type: entity
        children:
          - sensor.terasa_mansarda_current_consumption
          - sensor.priza_centrala_termica_energy_power
          - sensor.priza_frigider_energy_power
          - sensor.priza_living_energy_power
        entity_id: sensor.putere_instantanee
        remaining:
          name: Alti consumatori
          color: '#295096'
        name: Consum total
        color: purple
        sort_group_by_parent: true
  - entities:
      - type: entity
        children:
          - sensor.terasa_parter_current_consumption
          - sensor.terasa_mansarda_current_consumption
        entity_id: sensor.terasa_mansarda_current_consumption
        add_entitites:
          - sensor.terasa_parter_current_consumption
        color: '#4DE738'
        name: Prize exterior
      - type: entity
        children:
          - sensor.priza_centrala_termica_energy_power
          - sensor.priza_pompa_basa_energy_power
        add_entitites:
          - sensor.priza_pompa_basa_energy_power
        entity_id: sensor.priza_centrala_termica_energy_power
        name: Utilitati
        color: red
      - type: entity
        entity_id: sensor.priza_frigider_energy_power
        children:
          - sensor.priza_frigider_energy_power
          - sensor.priza_cuptor_microunde_energy_power
          - sensor.priza_espressor_energy_power
          - sensor.priza_uscator_prosoape_energy_power
          - sensor.priza_masina_spalat_rufe_energy_power
        add_entities:
          - sensor.priza_cuptor_microunde_energy_power
          - sensor.priza_espressor_energy_power
          - sensor.priza_uscator_prosoape_energy_power
          - sensor.priza_masina_spalat_rufe_energy_power
        color: orange
        name: Electrocasnice
      - type: entity
        children:
          - sensor.garaj_current_consumption
          - sensor.priza_living_energy_power
          - sensor.priza_living_2_energy_power
          - sensor.priza_living_3_energy_power
          - sensor.priza_birou_1_energy_power
          - sensor.priza_birou_2_energy_power
          - sensor.priza_birou_3_energy_power
          - sensor.priza_retea_mansarda_energy_power_2
        add_entities:
          - sensor.garaj_current_consumption
          - sensor.priza_living_2_energy_power
          - sensor.priza_living_3_energy_power
          - sensor.priza_birou_1_energy_power
          - sensor.priza_birou_2_energy_power
          - sensor.priza_birou_3_energy_power
          - sensor.priza_retea_mansarda_energy_power_2
        subtract_entities:
          - sensor.terasa_mansarda_current_consumption
        entity_id: sensor.priza_living_energy_power
        name: IT & Media
        color_on_state: false
    sort_by: state
    sort_dir: desc
    sort_group_by_parent: true
  - entities:
      - type: entity
        children: []
        entity_id: sensor.garaj_current_consumption
        name: Garaj
      - type: entity
        children: []
        entity_id: sensor.priza_centrala_termica_energy_power
        color: red
        name: Centrala termica
      - type: entity
        children: []
        entity_id: sensor.priza_pompa_basa_energy_power
        color: red
        name: Pompa basa
      - type: entity
        children: []
        entity_id: sensor.terasa_parter_current_consumption
        color: '#4DE738'
        name: Terasa parter
      - type: entity
        children: []
        entity_id: sensor.terasa_mansarda_current_consumption
        color: '#4DE738'
        name: Terasa mansarda
      - type: entity
        entity_id: sensor.priza_frigider_energy_power
        children: []
        color: orange
        name: Frigider
      - type: entity
        children: []
        entity_id: sensor.priza_cuptor_microunde_energy_power
        color: orange
        name: Cuptor microunde
      - type: entity
        children: []
        entity_id: sensor.priza_espressor_energy_power
        color: orange
        name: Espressor
      - type: entity
        children: []
        entity_id: sensor.priza_uscator_prosoape_energy_power
        color: orange
        name: Uscator prosoape
      - type: entity
        children: []
        entity_id: sensor.priza_masina_spalat_rufe_energy_power
        color: orange
        name: Masina spalat rufe
      - type: entity
        children: []
        entity_id: sensor.priza_living_energy_power
        name: Living 1
      - type: entity
        children: []
        entity_id: sensor.priza_living_2_energy_power
        name: Living 2
      - type: entity
        children: []
        entity_id: sensor.priza_living_3_energy_power
        name: Living 3
      - type: entity
        children: []
        entity_id: sensor.priza_birou_1_energy_power
        name: Birou 1
      - type: entity
        children: []
        entity_id: sensor.priza_birou_2_energy_power
        name: Birou 2
      - type: entity
        children: []
        entity_id: sensor.priza_birou_3_energy_power
        name: Birou 3
      - type: entity
        children: []
        entity_id: sensor.priza_retea_mansarda_energy_power_2
        name: Retea mansarda
    sort_by: state
    sort_dir: desc
    sort_group_by_parent: true
    min_width: 10
```
